#
# Wordless: Tagsets - spaCy Spanish Tagset
#
# Copyright (C) 2018-2020  Ye Lei (叶磊)
#
# This source file is licensed under GNU GPLv3.
# For details, see: https://github.com/BLKSerene/Wordless/blob/master/LICENSE.txt
#
# All other rights reserved.
#

#
# spaCy Spanish Tagset: https://github.com/explosion/spaCy/blob/master/spacy/lang/es/tag_map.py
#
# Universal POS Tags: http://universaldependencies.org/u/pos/all.html
#

mappings = [
    ['ADJ___', 'ADJ', '', ''],
    ['ADJ__AdpType=Prep', 'ADJ', '', ''],
    ['ADJ__AdpType=Preppron|Gender=Masc|Number=Sing', 'ADV', '', ''],
    ['ADJ__AdvType=Tim', 'ADJ', '', ''],
    ['ADJ__Gender=Fem|Number=Plur', 'ADJ', '', ''],
    ['ADJ__Gender=Fem|Number=Plur|NumType=Ord', 'ADJ', '', ''],
    ['ADJ__Gender=Fem|Number=Plur|VerbForm=Part', 'ADJ', '', ''],
    ['ADJ__Gender=Fem|Number=Sing', 'ADJ', '', ''],
    ['ADJ__Gender=Fem|Number=Sing|NumType=Ord', 'ADJ', '', ''],
    ['ADJ__Gender=Fem|Number=Sing|VerbForm=Part', 'ADJ', '', ''],
    ['ADJ__Gender=Masc', 'ADJ', '', ''],
    ['ADJ__Gender=Masc|Number=Plur', 'ADJ', '', ''],
    ['ADJ__Gender=Masc|Number=Plur|NumType=Ord', 'ADJ', '', ''],
    ['ADJ__Gender=Masc|Number=Plur|VerbForm=Part', 'ADJ', '', ''],
    ['ADJ__Gender=Masc|Number=Sing', 'ADJ', '', ''],
    ['ADJ__Gender=Masc|Number=Sing|NumType=Ord', 'ADJ', '', ''],
    ['ADJ__Gender=Masc|Number=Sing|VerbForm=Part', 'ADJ', '', ''],
    ['ADJ__Number=Plur', 'ADJ', '', ''],
    ['ADJ__Number=Sing', 'ADJ', '', ''],

    ['ADP', 'ADP', '', ''],
    ['ADP__AdpType=Prep', 'ADP', '', ''],
    ['ADP__AdpType=Preppron|Gender=Fem|Number=Sing', 'ADP', '', ''],
    ['ADP__AdpType=Preppron|Gender=Masc|Number=Plur', 'ADP', '', ''],
    ['ADP__AdpType=Preppron|Gender=Masc|Number=Sing', 'ADP', '', ''],

    ['ADV___', 'ADV', '', ''],
    ['ADV__AdpType=Prep', 'ADV', '', ''],
    ['ADV__AdpType=Preppron|Gender=Masc|Number=Sing', 'ADV', '', ''],
    ['ADV__AdvType=Tim', 'ADV', '', ''],
    ['ADV__Gender=Masc|Number=Sing', 'ADV', '', ''],
    ['ADV__Mood=Ind|Number=Sing|Person=3|Tense=Imp|VerbForm=Fin', 'ADV', '', ''],
    ['ADV__Negative=Neg', 'ADV', '', ''],
    ['ADV__Number=Plur', 'ADV', '', ''],
    ['ADV__Polarity=Neg', 'ADV', '', ''],

    ['AUX__Gender=Fem|Number=Plur|Tense=Past|VerbForm=Part', 'AUX', '', ''],
    ['AUX__Gender=Fem|Number=Sing|Tense=Past|VerbForm=Part', 'AUX', '', ''],
    ['AUX__Gender=Masc|Number=Plur|Tense=Past|VerbForm=Part', 'AUX', '', ''],
    ['AUX__Gender=Masc|Number=Sing|Tense=Past|VerbForm=Part', 'AUX', '', ''],
    ['AUX__Mood=Cnd|Number=Plur|Person=1|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Cnd|Number=Plur|Person=3|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Cnd|Number=Sing|Person=1|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Cnd|Number=Sing|Person=2|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Cnd|Number=Sing|Person=3|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Imp|Number=Plur|Person=3|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Imp|Number=Sing|Person=2|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Imp|Number=Sing|Person=3|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Ind|Number=Plur|Person=1|Tense=Fut|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Ind|Number=Plur|Person=1|Tense=Imp|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Ind|Number=Plur|Person=1|Tense=Past|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Ind|Number=Plur|Person=1|Tense=Pres|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Ind|Number=Plur|Person=2|Tense=Pres|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Ind|Number=Plur|Person=3|Tense=Fut|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Ind|Number=Plur|Person=3|Tense=Imp|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Ind|Number=Plur|Person=3|Tense=Past|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Ind|Number=Plur|Person=3|Tense=Pres|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Ind|Number=Sing|Person=1|Tense=Fut|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Ind|Number=Sing|Person=1|Tense=Imp|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Ind|Number=Sing|Person=1|Tense=Past|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Ind|Number=Sing|Person=1|Tense=Pres|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Ind|Number=Sing|Person=2|Tense=Fut|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Ind|Number=Sing|Person=2|Tense=Imp|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Ind|Number=Sing|Person=2|Tense=Pres|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Ind|Number=Sing|Person=3|Tense=Fut|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Ind|Number=Sing|Person=3|Tense=Imp|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Ind|Number=Sing|Person=3|Tense=Past|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Sub|Number=Plur|Person=1|Tense=Imp|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Sub|Number=Plur|Person=1|Tense=Pres|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Sub|Number=Plur|Person=3|Tense=Imp|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Sub|Number=Plur|Person=3|Tense=Pres|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Sub|Number=Sing|Person=1|Tense=Imp|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Sub|Number=Sing|Person=1|Tense=Pres|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Sub|Number=Sing|Person=2|Tense=Pres|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Sub|Number=Sing|Person=3|Tense=Imp|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Sub|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__VerbForm=Ger', 'AUX', '', ''],
    ['AUX__VerbForm=Inf', 'AUX', '', ''],

    ['CONJ___', 'CONJ', '', ''],
    ['CCONJ___', 'CCONJ', '', ''],
    ['SCONJ___', 'SCONJ', '', ''],

    ['DET', 'DET', '', ''],
    ['DET__Definite=Def|Gender=Fem|Number=Plur|PronType=Art', 'DET', '', ''],
    ['DET__Definite=Def|Gender=Fem|Number=Sing|PronType=Art', 'DET', '', ''],
    ['DET__Definite=Def|Gender=Masc|Number=Plur|PronType=Art', 'DET', '', ''],
    ['DET__Definite=Def|Gender=Masc|Number=Sing|PronType=Art', 'DET', '', ''],
    ['DET__Definite=Def|Gender=Masc|PronType=Art', 'DET', '', ''],
    ['DET__Definite=Def|Number=Sing|PronType=Art', 'DET', '', ''],
    ['DET__Definite=Ind|Gender=Fem|Number=Plur|PronType=Art', 'DET', '', ''],
    ['DET__Definite=Ind|Gender=Fem|Number=Sing|NumType=Card|PronType=Art', 'DET', '', ''],
    ['DET__Definite=Ind|Gender=Fem|Number=Sing|PronType=Art', 'DET', '', ''],
    ['DET__Definite=Ind|Gender=Masc|Number=Plur|PronType=Art', 'DET', '', ''],
    ['DET__Definite=Ind|Gender=Masc|Number=Sing|NumType=Card|PronType=Art', 'DET', '', ''],
    ['DET__Definite=Ind|Gender=Masc|Number=Sing|PronType=Art', 'DET', '', ''],
    ['DET__Gender=Fem|Number=Plur|Number[psor]=Plur|Person=1|Poss=Yes|PronType=Prs', 'DET', '', ''],
    ['DET__Gender=Fem|Number=Plur|Number[psor]=Plur|Person=2|Poss=Yes|PronType=Prs', 'DET', '', ''],
    ['DET__Gender=Fem|Number=Plur|Person=3|Poss=Yes|PronType=Prs', 'DET', '', ''],
    ['DET__Gender=Fem|Number=Plur|PronType=Art', 'DET', '', ''],
    ['DET__Gender=Fem|Number=Plur|PronType=Dem', 'DET', '', ''],
    ['DET__Gender=Fem|Number=Plur|PronType=Ind', 'DET', '', ''],
    ['DET__Gender=Fem|Number=Sing|Number[psor]=Plur|Person=1|Poss=Yes|PronType=Prs', 'DET', '', ''],
    ['DET__Gender=Fem|Number=Sing|Number[psor]=Plur|Person=2|Poss=Yes|PronType=Prs', 'DET', '', ''],
    ['DET__Gender=Fem|Number=Sing|Number[psor]=Sing|Person=1|Poss=Yes|PronType=Prs', 'DET', '', ''],
    ['DET__Gender=Fem|Number=Sing|Person=3|Poss=Yes|PronType=Prs', 'DET', '', ''],
    ['DET__Gender=Fem|Number=Sing|PronType=Art', 'DET', '', ''],
    ['DET__Gender=Fem|Number=Sing|PronType=Dem', 'DET', '', ''],
    ['DET__Gender=Fem|Number=Sing|PronType=Ind', 'DET', '', ''],
    ['DET__Gender=Fem|Number=Sing|PronType=Int', 'DET', '', ''],
    ['DET__Gender=Masc|Number=Plur|Number[psor]=Plur|Person=1|Poss=Yes|PronType=Prs', 'DET', '', ''],
    ['DET__Gender=Masc|Number=Plur|Person=3|Poss=Yes|PronType=Prs', 'DET', '', ''],
    ['DET__Gender=Masc|Number=Plur|PronType=Art', 'DET', '', ''],
    ['DET__Gender=Masc|Number=Plur|PronType=Dem', 'DET', '', ''],
    ['DET__Gender=Masc|Number=Plur|PronType=Ind', 'DET', '', ''],
    ['DET__Gender=Masc|Number=Sing|Number[psor]=Plur|Person=1|Poss=Yes|PronType=Prs', 'DET', '', ''],
    ['DET__Gender=Masc|Number=Sing|Number[psor]=Sing|Person=1|Poss=Yes|PronType=Prs', 'DET', '', ''],
    ['DET__Gender=Masc|Number=Sing|Person=3|Poss=Yes|PronType=Prs', 'DET', '', ''],
    ['DET__Gender=Masc|Number=Sing|PronType=Art', 'DET', '', ''],
    ['DET__Gender=Masc|Number=Sing|PronType=Dem', 'DET', '', ''],
    ['DET__Gender=Masc|Number=Sing|PronType=Ind', 'DET', '', ''],
    ['DET__Gender=Masc|Number=Sing|PronType=Int', 'DET', '', ''],
    ['DET__Gender=Masc|Number=Sing|PronType=Tot', 'DET', '', ''],
    ['DET__Number=Plur|Number[psor]=Sing|Person=1|Poss=Yes|PronType=Prs', 'DET', '', ''],
    ['DET__Number=Plur|Number[psor]=Sing|Person=2|Poss=Yes|PronType=Prs', 'DET', '', ''],
    ['DET__Number=Plur|Person=3|Poss=Yes|PronType=Prs', 'DET', '', ''],
    ['DET__Number=Plur|PronType=Dem', 'DET', '', ''],
    ['DET__Number=Plur|PronType=Ind', 'DET', '', ''],
    ['DET__Number=Sing|Number[psor]=Sing|Person=1|Poss=Yes|PronType=Prs', 'DET', '', ''],
    ['DET__Number=Sing|Number[psor]=Sing|Person=2|Poss=Yes|PronType=Prs', 'DET', '', ''],
    ['DET__Number=Sing|Person=3|Poss=Yes|PronType=Prs', 'DET', '', ''],
    ['DET__Number=Sing|PronType=Dem', 'DET', '', ''],
    ['DET__Number=Sing|PronType=Ind', 'DET', '', ''],
    ['DET__PronType=Int', 'DET', '', ''],
    ['DET__PronType=Rel', 'DET', '', ''],

    ['INTJ___', 'INTJ', '', ''],

    ['NOUN___', 'NOUN', '', ''],
    ['NOUN__AdvType=Tim', 'NOUN', '', ''],
    ['NOUN__AdvType=Tim|Gender=Masc|Number=Sing', 'NOUN', '', ''],
    ['NOUN__Gender=Fem', 'NOUN', '', ''],
    ['NOUN__Gender=Fem|Number=Plur', 'NOUN', '', ''],
    ['NOUN__Gender=Fem|Number=Sing', 'NOUN', '', ''],
    ['NOUN__Gender=Masc', 'NOUN', '', ''],
    ['NOUN__Gender=Masc|Number=Plur', 'NOUN', '', ''],
    ['NOUN__Gender=Masc|Number=Sing', 'NOUN', '', ''],
    ['NOUN__Gender=Masc|Number=Sing|VerbForm=Part', 'NOUN', '', ''],
    ['NOUN__Number=Plur', 'NOUN', '', ''],
    ['NOUN__Number=Sing', 'NOUN', '', ''],
    ['NOUN__NumForm=Digit', 'NOUN', '', ''],
    ['PROPN___', 'PROPN', '', ''],

    ['NUM__Gender=Fem|Number=Plur|NumType=Card', 'NUM', '', ''],
    ['NUM__Gender=Fem|Number=Sing|NumType=Card', 'NUM', '', ''],
    ['NUM__Gender=Masc|Number=Plur|NumType=Card', 'NUM', '', ''],
    ['NUM__Gender=Masc|Number=Sing|NumType=Card', 'NUM', '', ''],
    ['NUM__Number=Plur|NumType=Card', 'NUM', '', ''],
    ['NUM__Number=Sing|NumType=Card', 'NUM', '', ''],
    ['NUM__NumForm=Digit', 'NUM', '', ''],
    ['NUM__NumForm=Digit|NumType=Card', 'NUM', '', ''],
    ['NUM__NumForm=Digit|NumType=Frac', 'NUM', '', ''],
    ['NUM__NumType=Card', 'NUM', '', ''],

    ['PART___', 'PART', '', ''],
    ['PART__Negative=Neg', 'PART', '', ''],

    ['PRON___', 'PRON', '', ''],
    ['PRON__Case=Acc|Gender=Fem|Number=Plur|Person=3|PronType=Prs', 'PRON', '', ''],
    ['PRON__Case=Acc|Gender=Fem|Number=Sing|Person=3|PronType=Prs', 'PRON', '', ''],
    ['PRON__Case=Acc|Gender=Masc|Number=Plur|Person=3|PronType=Prs', 'PRON', '', ''],
    ['PRON__Case=Acc|Gender=Masc|Number=Sing|Person=3|PronType=Prs', 'PRON', '', ''],
    ['PRON__Case=Acc|Number=Plur|Person=3|PronType=Prs', 'PRON', '', ''],
    ['PRON__Case=Acc|Number=Sing|Person=3|PronType=Prs', 'PRON', '', ''],
    ['PRON__Case=Acc|Person=3|PronType=Prs', 'PRON', '', ''],
    ['PRON__Case=Dat|Number=Plur|Person=3|PronType=Prs', 'PRON', '', ''],
    ['PRON__Case=Dat|Number=Sing|Person=3|PronType=Prs', 'PRON', '', ''],
    ['PRON__Case=Nom|Number=Sing|Person=1|PronType=Prs', 'PRON', '', ''],
    ['PRON__Case=Nom|Number=Sing|Person=2|PronType=Prs', 'PRON', '', ''],
    ['PRON__Gender=Fem|Number=Plur|Number[psor]=Plur|Person=1|Poss=Yes|PronType=Prs', 'PRON', '', ''],
    ['PRON__Gender=Fem|Number=Plur|Person=3|Poss=Yes|PronType=Prs', 'PRON', '', ''],
    ['PRON__Gender=Fem|Number=Plur|Person=3|PronType=Prs', 'PRON', '', ''],
    ['PRON__Gender=Fem|Number=Plur|PronType=Dem', 'PRON', '', ''],
    ['PRON__Gender=Fem|Number=Plur|PronType=Ind', 'PRON', '', ''],
    ['PRON__Gender=Fem|Number=Plur|PronType=Int', 'PRON', '', ''],
    ['PRON__Gender=Fem|Number=Plur|PronType=Rel', 'PRON', '', ''],
    ['PRON__Gender=Fem|Number=Sing|Number[psor]=Plur|Person=1|Poss=Yes|PronType=Prs', 'PRON', '', ''],
    ['PRON__Gender=Fem|Number=Sing|Number[psor]=Sing|Person=1|Poss=Yes|PronType=Prs', 'PRON', '', ''],
    ['PRON__Gender=Fem|Number=Sing|Number[psor]=Sing|Person=2|Poss=Yes|PronType=Prs', 'PRON', '', ''],
    ['PRON__Gender=Fem|Number=Sing|Person=1|PronType=Prs', 'PRON', '', ''],
    ['PRON__Gender=Fem|Number=Sing|Person=3|Poss=Yes|PronType=Prs', 'PRON', '', ''],
    ['PRON__Gender=Fem|Number=Sing|Person=3|PronType=Prs', 'PRON', '', ''],
    ['PRON__Gender=Fem|Number=Sing|PronType=Dem', 'PRON', '', ''],
    ['PRON__Gender=Fem|Number=Sing|PronType=Ind', 'PRON', '', ''],
    ['PRON__Gender=Fem|Number=Sing|PronType=Rel', 'PRON', '', ''],
    ['PRON__Gender=Masc|Number=Plur|Person=1|PronType=Prs', 'PRON', '', ''],
    ['PRON__Gender=Masc|Number=Plur|Person=2|Poss=Yes|PronType=Prs', 'PRON', '', ''],
    ['PRON__Gender=Masc|Number=Plur|Person=3|PronType=Prs', 'PRON', '', ''],
    ['PRON__Gender=Masc|Number=Plur|PronType=Dem', 'PRON', '', ''],
    ['PRON__Gender=Masc|Number=Plur|PronType=Ind', 'PRON', '', ''],
    ['PRON__Gender=Masc|Number=Plur|PronType=Int', 'PRON', '', ''],
    ['PRON__Gender=Masc|Number=Plur|PronType=Rel', 'PRON', '', ''],
    ['PRON__Gender=Masc|Number=Sing|Number[psor]=Plur|Person=1|Poss=Yes|PronType=Prs', 'PRON', '', ''],
    ['PRON__Gender=Masc|Number=Sing|Number[psor]=Sing|Person=1|Poss=Yes|PronType=Prs', 'PRON', '', ''],
    ['PRON__Gender=Masc|Number=Sing|Number[psor]=Sing|Person=2|Poss=Yes|PronType=Prs', 'PRON', '', ''],
    ['PRON__Gender=Masc|Number=Sing|Person=3|Poss=Yes|PronType=Prs', 'PRON', '', ''],
    ['PRON__Gender=Masc|Number=Sing|Person=3|PronType=Prs', 'PRON', '', ''],
    ['PRON__Gender=Masc|Number=Sing|PronType=Dem', 'PRON', '', ''],
    ['PRON__Gender=Masc|Number=Sing|PronType=Ind', 'PRON', '', ''],
    ['PRON__Gender=Masc|Number=Sing|PronType=Int', 'PRON', '', ''],
    ['PRON__Gender=Masc|Number=Sing|PronType=Rel', 'PRON', '', ''],
    ['PRON__Gender=Masc|Number=Sing|PronType=Tot', 'PRON', '', ''],
    ['PRON__Number=Plur|Person=1', 'PRON', '', ''],
    ['PRON__Number=Plur|Person=1|PronType=Prs', 'PRON', '', ''],
    ['PRON__Number=Plur|Person=2|Polite=Form|PronType=Prs', 'PRON', '', ''],
    ['PRON__Number=Plur|Person=2|PronType=Prs', 'PRON', '', ''],
    ['PRON__Number=Plur|Person=3|Poss=Yes|PronType=Prs', 'PRON', '', ''],
    ['PRON__Number=Plur|Person=3|PronType=Prs', 'PRON', '', ''],
    ['PRON__Number=Plur|PronType=Dem', 'PRON', '', ''],
    ['PRON__Number=Plur|PronType=Ind', 'PRON', '', ''],
    ['PRON__Number=Plur|PronType=Int', 'PRON', '', ''],
    ['PRON__Number=Plur|PronType=Rel', 'PRON', '', ''],
    ['PRON__Number=Sing|Person=1', 'PRON', '', ''],
    ['PRON__Number=Sing|Person=1|PrepCase=Pre|PronType=Prs', 'PRON', '', ''],
    ['PRON__Number=Sing|Person=1|PronType=Prs', 'PRON', '', ''],
    ['PRON__Number=Sing|Person=2', 'PRON', '', ''],
    ['PRON__Number=Sing|Person=2|Polite=Form|PronType=Prs', 'PRON', '', ''],
    ['PRON__Number=Sing|Person=2|PrepCase=Pre|PronType=Prs', 'PRON', '', ''],
    ['PRON__Number=Sing|Person=2|PronType=Prs', 'PRON', '', ''],
    ['PRON__Number=Sing|Person=3|Poss=Yes|PronType=Prs', 'PRON', '', ''],
    ['PRON__Number=Sing|Person=3|PronType=Prs', 'PRON', '', ''],
    ['PRON__Number=Sing|PronType=Dem', 'PRON', '', ''],
    ['PRON__Number=Sing|PronType=Ind', 'PRON', '', ''],
    ['PRON__Number=Sing|PronType=Int', 'PRON', '', ''],
    ['PRON__Number=Sing|PronType=Rel', 'PRON', '', ''],
    ['PRON__Person=1|PronType=Prs', 'PRON', '', ''],
    ['PRON__Person=3', 'PRON', '', ''],
    ['PRON__Person=3|PrepCase=Pre|PronType=Prs', 'PRON', '', ''],
    ['PRON__Person=3|PronType=Prs', 'PRON', '', ''],
    ['PRON__PronType=Ind', 'PRON', '', ''],
    ['PRON__PronType=Int', 'PRON', '', ''],
    ['PRON__PronType=Rel', 'PRON', '', ''],

    ['VERB__Gender=Fem|Number=Plur|Tense=Past|VerbForm=Part', 'VERB', '', ''],
    ['VERB__Gender=Fem|Number=Sing|Tense=Past|VerbForm=Part', 'VERB', '', ''],
    ['VERB__Gender=Masc|Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Gender=Masc|Number=Plur|Tense=Past|VerbForm=Part', 'VERB', '', ''],
    ['VERB__Gender=Masc|Number=Sing|Tense=Past|VerbForm=Part', 'VERB', '', ''],
    ['VERB__Mood=Cnd|Number=Plur|Person=1|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Cnd|Number=Plur|Person=3|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Cnd|Number=Sing|Person=1|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Cnd|Number=Sing|Person=2|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Cnd|Number=Sing|Person=3|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Imp|Number=Plur|Person=1|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Imp|Number=Plur|Person=2|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Imp|Number=Plur|Person=3|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Imp|Number=Sing|Person=2|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Imp|Number=Sing|Person=3|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Ind|Number=Plur|Person=1|Tense=Fut|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Ind|Number=Plur|Person=1|Tense=Imp|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Ind|Number=Plur|Person=1|Tense=Past|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Ind|Number=Plur|Person=1|Tense=Pres|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Ind|Number=Plur|Person=2|Tense=Pres|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Ind|Number=Plur|Person=3|Tense=Fut|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Ind|Number=Plur|Person=3|Tense=Imp|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Ind|Number=Plur|Person=3|Tense=Past|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Ind|Number=Plur|Person=3|Tense=Pres|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Ind|Number=Sing|Person=1|Tense=Fut|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Ind|Number=Sing|Person=1|Tense=Imp|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Ind|Number=Sing|Person=1|Tense=Past|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Ind|Number=Sing|Person=1|Tense=Pres|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Ind|Number=Sing|Person=2|Tense=Fut|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Ind|Number=Sing|Person=2|Tense=Imp|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Ind|Number=Sing|Person=2|Tense=Past|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Ind|Number=Sing|Person=2|Tense=Pres|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Ind|Number=Sing|Person=3|Tense=Fut|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Ind|Number=Sing|Person=3|Tense=Imp|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Ind|Number=Sing|Person=3|Tense=Past|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Ind|Person=3|Tense=Pres|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Sub|Number=Plur|Person=1|Tense=Imp|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Sub|Number=Plur|Person=1|Tense=Pres|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Sub|Number=Plur|Person=2|Tense=Pres|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Sub|Number=Plur|Person=3|Tense=Imp|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Sub|Number=Plur|Person=3|Tense=Pres|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Sub|Number=Sing|Person=1|Tense=Imp|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Sub|Number=Sing|Person=1|Tense=Pres|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Sub|Number=Sing|Person=2|Tense=Pres|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Sub|Number=Sing|Person=3|Tense=Imp|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Sub|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__VerbForm=Ger', 'VERB', '', ''],
    ['VERB__VerbForm=Inf', 'VERB', '', ''],

    ['PUNCT___', 'PUNCT', '', ''],
    ['PUNCT__PunctSide=Fin|PunctType=Brck', 'PUNCT', '', ''],
    ['PUNCT__PunctSide=Fin|PunctType=Excl', 'PUNCT', '', ''],
    ['PUNCT__PunctSide=Fin|PunctType=Qest', 'PUNCT', '', ''],
    ['PUNCT__PunctSide=Ini|PunctType=Brck', 'PUNCT', '', ''],
    ['PUNCT__PunctSide=Ini|PunctType=Excl', 'PUNCT', '', ''],
    ['PUNCT__PunctSide=Ini|PunctType=Qest', 'PUNCT', '', ''],
    ['PUNCT__PunctType=Colo', 'PUNCT', '', ''],
    ['PUNCT__PunctType=Comm', 'PUNCT', '', ''],
    ['PUNCT__PunctType=Dash', 'PUNCT', '', ''],
    ['PUNCT__PunctType=Peri', 'PUNCT', '', ''],
    ['PUNCT__PunctType=Quot', 'PUNCT', '', ''],
    ['PUNCT__PunctType=Semi', 'PUNCT', '', ''],

    ['SYM___', 'SYM', '', ''],
    ['SYM__NumForm=Digit', 'SYM', '', ''],
    ['SYM__NumForm=Digit|NumType=Frac', 'SYM', '', ''],

    ['_SP', 'X', '', ''],
    ['X___', 'X', '', '']
]
