#
# Wordless: CI - Azure Pipelines
#
# Copyright (C) 2018-2019  Ye Lei (叶磊)
#
# This source file is licensed under GNU GPLv3.
# For details, see: https://github.com/BLKSerene/Wordless/blob/master/LICENSE.txt
#
# All other rights reserved.
#

jobs:
# Windows
- job: "Windows"

  pool:
    vmImage: windows-2019

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7.x' 
      architecture: 'x64'

  # Check Python version
  - script: |
      python --version
    displayName: 'Check Python version'

  # Install dependencies
  - script: |
      pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  # Download data
  - script: |
      python downloaders/wordless_downloader_ci.py
    displayName: 'Download data'

  # Run tests
  - script: |
      cd src
      pytest wordless_tests/wordless_text/wordless_text_processing/test_sentence_tokenization.py
      pytest wordless_tests/wordless_text/wordless_text_processing/test_word_tokenization.py
      pytest wordless_tests/wordless_text/wordless_text_processing/test_word_detokenization.py
      pytest wordless_tests/wordless_text/wordless_text_processing/test_pos_tagging.py
      pytest wordless_tests/wordless_text/wordless_text_processing/test_lemmatization.py
      pytest wordless_tests/wordless_text/wordless_text_processing/test_stop_words.py
      pytest --ignore=wordless_tests/test_init.py --ignore=wordless_tests/wordless_text/wordless_text_processing/
    displayName: 'Run tests'

# macOS
- job: "macOS"

  pool:
    vmImage: macOS-10.14

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7.x' 

  # Check Python version
  - script: |
      python3 --version
    displayName: 'Check Python version'

  # Install dependencies
  - script: |
      pip3 install --upgrade pip
      pip3 install -r requirements.txt
    displayName: 'Install dependencies'

  # Download data
  - script: |
      python3 downloaders/wordless_downloader_ci.py
    displayName: 'Download data'

  # Run tests
  - script: |
      cd src
      pytest wordless_tests/wordless_text/wordless_text_processing/test_sentence_tokenization.py
      pytest wordless_tests/wordless_text/wordless_text_processing/test_word_tokenization.py
      pytest wordless_tests/wordless_text/wordless_text_processing/test_word_detokenization.py
      pytest wordless_tests/wordless_text/wordless_text_processing/test_pos_tagging.py
      pytest wordless_tests/wordless_text/wordless_text_processing/test_lemmatization.py
      pytest wordless_tests/wordless_text/wordless_text_processing/test_stop_words.py
      pytest --ignore=wordless_tests/test_init.py --ignore=wordless_tests/wordless_text/wordless_text_processing/
    displayName: 'Run tests'

# Linux
- job: "Linux"

  pool:
    vmImage: ubuntu-16.04

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7.x' 

  # Check Python version
  - script: |
      python3.7 --version
    displayName: 'Check Python version'

  # Install dependencies
  - script: |
      pip3.7 install --upgrade pip
      pip3.7 install -r requirements.txt
    displayName: 'Install dependencies'

  # Download data
  - script: |
      python3.7 downloaders/wordless_downloader_ci.py
    displayName: 'Download data'

  # Run tests
  - script: |
      cd src
      pytest wordless_tests/wordless_text/wordless_text_processing/test_sentence_tokenization.py
      pytest wordless_tests/wordless_text/wordless_text_processing/test_word_tokenization.py
      pytest wordless_tests/wordless_text/wordless_text_processing/test_word_detokenization.py
      pytest wordless_tests/wordless_text/wordless_text_processing/test_pos_tagging.py
      pytest wordless_tests/wordless_text/wordless_text_processing/test_lemmatization.py
      pytest wordless_tests/wordless_text/wordless_text_processing/test_stop_words.py
      pytest --ignore=wordless_tests/test_init.py --ignore=wordless_tests/wordless_text/wordless_text_processing/
    displayName: 'Run tests'
