#
# Wordless: CI - Azure Pipelines
#
# Copyright (C) 2018-2021  Ye Lei (叶磊)
#
# This source file is licensed under GNU GPLv3.
# For details, see: https://github.com/BLKSerene/Wordless/blob/master/LICENSE.txt
#
# All other rights reserved.
#

jobs:
# Windows
- job: "Windows"

  pool:
    vmImage: vs2017-win2016

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8.x' 
      architecture: 'x64'

  # Check Python version
  - script: |
      python --version
    displayName: 'Check Python version'

  # Install dependencies
  - script: |
      pip install --upgrade pip setuptools
      pip install --requirement requirements.txt
    displayName: 'Install dependencies'

  # Download data
  - script: |
      python downloaders/wl_downloader_ci.py
    displayName: 'Download data'

  # Run tests
  - script: |
      cd src

      pytest wl_tests/test_overview.py
      pytest wl_tests/test_wordlist.py
      pytest wl_tests/test_ngram.py

      pytest wl_tests/wl_text/test_sentence_tokenization.py
      pytest wl_tests/wl_text/test_word_tokenization.py
      pytest wl_tests/wl_text/test_word_detokenization.py
      pytest wl_tests/wl_text/test_pos_tagging.py
      pytest wl_tests/wl_text/test_lemmatization.py

      pytest --ignore=wl_tests/wl_text/test_sentence_tokenization.py --ignore=wl_tests/wl_text/test_word_tokenization.py --ignore=wl_tests/wl_text/test_word_detokenization.py --ignore=wl_tests/wl_text/test_pos_tagging.py --ignore=wl_tests/wl_text/test_lemmatization.py --ignore=wl_tests/test_overview.py --ignore=wl_tests/test_wordlist.py --ignore=wl_tests/test_ngram.py
    displayName: 'Run tests'

# macOS
- job: "macOS"

  pool:
    vmImage: macOS-10.14

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8.x' 

  # Check Python version
  - script: |
      python3 --version
    displayName: 'Check Python version'

  # Install dependencies
  - script: |
      brew install libomp
      export CC=/usr/bin/clang
      export CXX=/usr/bin/clang++
      export CPPFLAGS="$CPPFLAGS -Xpreprocessor -fopenmp"
      export CFLAGS="$CFLAGS -I/usr/local/opt/libomp/include"
      export CXXFLAGS="$CXXFLAGS -I/usr/local/opt/libomp/include"
      export LDFLAGS="$LDFLAGS -Wl,-rpath,/usr/local/opt/libomp/lib -L/usr/local/opt/libomp/lib -lomp"

      pip3 install --upgrade pip setuptools
      pip3 install --requirement requirements.txt
    displayName: 'Install dependencies'

  # Download data
  - script: |
      python3 downloaders/wl_downloader_ci.py
    displayName: 'Download data'

  # Run tests
  - script: |
      cd src

      pytest wl_tests/test_overview.py
      pytest wl_tests/test_wordlist.py
      pytest wl_tests/test_ngram.py

      pytest wl_tests/wl_text/test_sentence_tokenization.py
      pytest wl_tests/wl_text/test_word_tokenization.py
      pytest wl_tests/wl_text/test_word_detokenization.py
      pytest wl_tests/wl_text/test_pos_tagging.py
      pytest wl_tests/wl_text/test_lemmatization.py

      pytest --ignore=wl_tests/wl_text/test_sentence_tokenization.py --ignore=wl_tests/wl_text/test_word_tokenization.py --ignore=wl_tests/wl_text/test_word_detokenization.py --ignore=wl_tests/wl_text/test_pos_tagging.py --ignore=wl_tests/wl_text/test_lemmatization.py --ignore=wl_tests/test_overview.py --ignore=wl_tests/test_wordlist.py --ignore=wl_tests/test_ngram.py
    displayName: 'Run tests'

# Linux
- job: "Linux"

  pool:
    vmImage: ubuntu-16.04

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8.x' 

  # Check Python version
  - script: |
      python3.8 --version
    displayName: 'Check Python version'

  # Install dependencies
  - script: |
      pip3.8 install --upgrade pip setuptools
      pip3.8 install numpy
      pip3.8 install --requirement requirements.txt
    displayName: 'Install dependencies'

  # Download data
  - script: |
      python3.8 downloaders/wl_downloader_ci.py
    displayName: 'Download data'

  # Run tests
  - script: |
      cd src

      pytest wl_tests/wl_text/test_sentence_tokenization.py
      pytest wl_tests/wl_text/test_word_tokenization.py
      pytest wl_tests/wl_text/test_word_detokenization.py
      pytest wl_tests/wl_text/test_pos_tagging.py
      pytest wl_tests/wl_text/test_lemmatization.py

      pytest --ignore=wl_tests/wl_text/test_sentence_tokenization.py --ignore=wl_tests/wl_text/test_word_tokenization.py --ignore=wl_tests/wl_text/test_word_detokenization.py --ignore=wl_tests/wl_text/test_pos_tagging.py --ignore=wl_tests/wl_text/test_lemmatization.py --ignore=wl_tests/test_overview.py --ignore=wl_tests/test_wordlist.py --ignore=wl_tests/test_ngram.py
    displayName: 'Run tests'
