# ----------------------------------------------------------------------
# Wordless: CI - Azure Pipelines
# Copyright (C) 2018-2023  Ye Lei (叶磊)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# ----------------------------------------------------------------------

variables:
  PIP_CACHE_DIR: $(Pipeline.Workspace)/.pip

jobs:
  # Windows
  - job: "Windows"

    pool:
      vmImage: windows-2019

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.10'
          architecture: 'x64'

      - task: Cache@2
        inputs:
          key: 'pip | "$(Agent.OS)" | requirements/requirements_tests.txt'
          restoreKeys: |
            pip | "$(Agent.OS)"
          path: $(PIP_CACHE_DIR)
        displayName: Cache pip packages

      # Install dependencies
      - script: |
          pip install --upgrade pip setuptools
          pip install --requirement requirements/requirements_tests.txt
          pip install --requirement requirements/requirements_no_deps.txt --no-deps
          :: Download models and data files
          python utils/wl_downloader_ci.py
        displayName: 'Install dependencies'

      # Run tests
      - script: |
          pytest tests/wl_tests_nlp/wl_tests_spacy/test_spacy_eng.py
          pytest tests/wl_tests_nlp/wl_tests_stanza/test_stanza_eng.py

          pytest tests/wl_tests_nlp/test_word_tokenization.py
          pytest tests/wl_tests_nlp/test_pos_tagging.py
          pytest tests/wl_tests_nlp/test_lemmatization.py

          pytest tests/wl_tests_nlp/ --ignore=tests/wl_tests_nlp/wl_tests_spacy --ignore=tests/wl_tests_nlp/wl_tests_stanza --ignore=tests/wl_tests_nlp/test_word_tokenization.py --ignore=tests/wl_tests_nlp/test_pos_tagging.py --ignore=tests/wl_tests_nlp/test_lemmatization.py
          pytest --ignore=tests/wl_tests_nlp
        displayName: 'Run tests'

  # macOS
  - job: "macOS"

    pool:
      vmImage: macOS-11

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.10'

      - task: Cache@2
        inputs:
          key: 'pip | "$(Agent.OS)" | requirements/requirements_tests.txt'
          restoreKeys: |
            pip | "$(Agent.OS)"
          path: $(PIP_CACHE_DIR)
        displayName: Cache pip packages

      # Install dependencies
      - script: |
          pip3 install --upgrade pip setuptools
          pip3 install --requirement requirements/requirements_tests.txt
          pip3 install --requirement requirements/requirements_no_deps.txt --no-deps
          # Download models and data files
          python3 utils/wl_downloader_ci.py
        displayName: 'Install dependencies'

      # Run tests
      - script: |
          pytest tests/wl_tests_nlp/wl_tests_spacy/test_spacy_eng.py
          pytest tests/wl_tests_nlp/wl_tests_stanza/test_stanza_eng.py

          pytest tests/wl_tests_nlp/test_word_tokenization.py
          pytest tests/wl_tests_nlp/test_pos_tagging.py
          pytest tests/wl_tests_nlp/test_lemmatization.py

          pytest tests/wl_tests_nlp/ --ignore=tests/wl_tests_nlp/wl_tests_spacy --ignore=tests/wl_tests_nlp/wl_tests_stanza --ignore=tests/wl_tests_nlp/test_word_tokenization.py --ignore=tests/wl_tests_nlp/test_pos_tagging.py --ignore=tests/wl_tests_nlp/test_lemmatization.py
          pytest --ignore=tests/wl_tests_nlp
        displayName: 'Run tests'

  # Linux
  - job: "Linux"

    pool:
      vmImage: ubuntu-20.04

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.10'

      - task: Cache@2
        inputs:
          key: 'pip | "$(Agent.OS)" | requirements/requirements_tests.txt'
          restoreKeys: |
            pip | "$(Agent.OS)"
          path: $(PIP_CACHE_DIR)
        displayName: Cache pip packages

      # Install dependencies
      - script: |
          pip3.10 install --upgrade pip setuptools
          pip3.10 install --requirement requirements/requirements_tests.txt
          pip3.10 install --requirement requirements/requirements_no_deps.txt --no-deps
          # Download models and data files
          python3.10 utils/wl_downloader_ci.py
        displayName: 'Install dependencies'

      # Run tests
      - script: |
          # Fix PyQt
          export QT_QPA_PLATFORM=offscreen

          pytest tests/wl_tests_nlp/wl_tests_spacy/test_spacy_eng.py
          pytest tests/wl_tests_nlp/wl_tests_stanza/test_stanza_eng.py

          pytest tests/wl_tests_nlp/test_word_tokenization.py
          pytest tests/wl_tests_nlp/test_pos_tagging.py
          pytest tests/wl_tests_nlp/test_lemmatization.py

          pytest tests/wl_tests_nlp/ --ignore=tests/wl_tests_nlp/wl_tests_spacy --ignore=tests/wl_tests_nlp/wl_tests_stanza --ignore=tests/wl_tests_nlp/test_word_tokenization.py --ignore=tests/wl_tests_nlp/test_pos_tagging.py --ignore=tests/wl_tests_nlp/test_lemmatization.py
          pytest --ignore=tests/wl_tests_nlp
        displayName: 'Run tests'
