# ----------------------------------------------------------------------
# Wordless: Tests - Language Examples
# Copyright (C) 2018-2023  Ye Lei (叶磊)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# ----------------------------------------------------------------------

# Encodings
ENCODING_ARA = '''اللُّغَةُ العَرَبِيَّة هي أكثر اللغات السامية تحدثًا، وإحدى أكثر اللغات انتشاراً في العالم، يتحدثها أكثر من 467 مليون نسمة،(1) ويتوزع متحدثوها في الوطن العربي، بالإضافة إلى العديد من المناطق الأخرى المجاورة كالأحواز وتركيا وتشاد ومالي والسنغال وإرتيريا وإثيوبيا وجنوب السودان وإيران. وبذلك فهي تحتل المركز الرابع أو الخامس من حيث اللغات الأكثر انتشارًا في العالم، وهي تحتل المركز الثالث تبعًا لعدد الدول التي تعترف بها كلغة رسمية؛ إذ تعترف بها 27 دولة كلغة رسمية، واللغة الرابعة من حيث عدد المستخدمين على الإنترنت. اللغةُ العربيةُ ذات أهمية قصوى لدى المسلمين، فهي عندَهم لغةٌ مقدسة إذ أنها لغة القرآن، وهي لغةُ الصلاة وأساسيةٌ في القيام بالعديد من العبادات والشعائرِ الإسلامية. العربيةُ هي أيضاً لغة شعائرية رئيسية لدى عدد من الكنائس المسيحية في الوطن العربي، كما كُتبَت بها كثير من أهمِّ الأعمال الدينية والفكرية اليهودية في العصور الوسطى. ارتفعتْ مكانةُ اللغةِ العربية إثْرَ انتشارِ الإسلام بين الدول إذ أصبحت لغة السياسة والعلم والأدب لقرون طويلة في الأراضي التي حكمها المسلمون. وللغة العربية تأثير مباشر وغير مباشر على كثير من اللغات الأخرى في العالم الإسلامي، كالتركية والفارسية والأمازيغية والكردية والأردية والماليزية والإندونيسية والألبانية وبعض اللغات الإفريقية الأخرى مثل الهاوسا والسواحيلية والتجرية والأمهرية والصومالية، وبعض اللغات الأوروبية وخاصةً المتوسطية كالإسبانية والبرتغالية والمالطية والصقلية؛ ودخلت الكثير من مصطلحاتها في اللغة الإنجليزية واللغات الأخرى، مثل أدميرال والتعريفة والكحول والجبر وأسماء النجوم. كما أنها تُدرَّس بشكل رسمي أو غير رسمي في الدول الإسلامية والدول الإفريقية المحاذية للوطن العربي.

العربية لغةٌ رسمية في كل دول الوطن العربي إضافة إلى كونها لغة رسمية في تشاد وإريتريا. وهي إحدى اللغات الرسمية الست في منظمة الأمم المتحدة، ويُحتفل باليوم العالمي للغة العربية في 18 ديسمبر كذكرى اعتماد العربية بين لغات العمل في الأمم المتحدة. وفي سنة 2011 صنفت بلومبيرغ بيزنس ويك اللغة العربية في المرتبة الرابعة من حيث اللغات الأكثر فائدة في الأعمال التجارية على مستوى العالم. "وفي 2013 نشر المجلس الثقافي البريطاني تقريرًا مفصلاً عن اللغات الأكثر طلباً في المملكة المتحدة تحت عنوان "لغات المستقبل" وتبين ان العربية تحتل المرتبة الثانية على مستوى العالم وفي 2017 احتلت المرتبة الرابعة. فيما يخص اللغات الأكثر جنيا للأرباح في بريطانيا تاتي العربية في المرتبة الثانية وفقا للمنظمة.

واللغة العربية من أغزر اللغات من حيث المادةِ اللغوية، فعلى سبيل المثال يحوي معجم لسان العرب لابن منظور من القرن الثالث عشر أكثر من 80 ألف مادة، بينما في اللغة الإنجليزية فإن قاموس صموئيل جونسون - وهو من أوائل من وضع قاموساً إنجليزياً من القرن الثامن عشر- يحتوي على 42 ألف كلمة.

تحتوي اللغة العربية 28 حرفاً مكتوباً. ويرى بعضُ اللغويين أنه يجب إضافة حرف الهمزة إلى حروف العربية، ليصبحَ عدد الحروف 29. تُكتب العربية من اليمين إلى اليسار - ومثلها اللغة الفارسية والعبرية على عكس كثير من اللغات العالمية - ومن أعلى الصفحة إلى أسفلها.'''
ENCODING_ZHO_CN = '''汉语又称中文、华语[3]、唐话[4]，概指由上古汉语（先秦雅言）发展而来、书面使用汉字的分析语，为汉藏语系最大的一支语族。如把整个汉语族视为单一语言，则汉语为世界使用人数最多的语言，目前全世界有五分之一人口将汉语做为母语或第二语言。

汉语在以其做为母语的地方会有不同的通称，且有多种方言变体，其中以北方汉语为基础的官话最为流行，其衍生而来的现代标准汉语（中华人民共和国的普通话、中华民国的国语、以及新加坡的标准华语）是大中华区的主要通用语。此外，汉语还是联合国正式语文[5]，并被上海合作组织等国际组织采用为官方语言。国际上常将“汉语”称为“中文”，这是因为其他国家（除日本外）均使用表音文字，对于“文”[6]与“语”[7]并不作区分，不符合汉语语法；然而华人使用表意文字，文字[8]并不等于语言[9]，作为母语人士不宜随之误用。[注 1]

对于汉语下属语言的分类，学界主要有两种观点，一种观点将汉语定义为语言，并将官话、赣语、闽语、粤语、客家话、吴语、湘语七大分支定义为一级方言；另一种观点则将汉语视为语族，七大分支因无法互相沟通而视为语支，而语支下面的各个分支被视为独立的语言[10]，如国际标准化组织就将汉语族分为13种语言：闽东语、晋语、官话、莆仙语、徽语、闽中语、赣语、客家话、湘语、闽北语、闽南语、吴语、粤语。无论用哪种观点，上述各种语言都是平等的，它们都是汉语里的一分子；而汉语是它们的集合体，并非专指它们当中的其中一种。

汉语使用的文字是汉字，以汉字写成的词、词组、句子、段落、文字作品，称为中文（又称华文、国文、汉文、唐文）。汉字是一种意音文字，表意之同时也具一定表音功能；而汉语属分析语，且声调辨义。

汉语包含书面语及口语两部分，古代书面语称为文言文，现代书面语一般指官话白话文，即使用标准官话语法、词汇的中文通行文体。粤港澳等地又流行夹杂文言文、官话白话文及粤语白话文的三及第文体，吴语区亦偶有人书写吴语白话文。汉字也被其他语言使用，并形成汉字文化圈。'''
ENCODING_ZHO_TW = '''漢語又稱中文、華語[3]、唐話[4]，概指由上古漢語（先秦雅言）發展而來、書面使用漢字的分析語，為漢藏語系最大的一支語族。如把整個漢語族視為單一語言，則漢語為世界使用人數最多的語言，目前全世界有五分之一人口將漢語做為母語或第二語言。

漢語在以其做為母語的地方會有不同的通稱，且有多種方言變體，其中以北方漢語為基礎的官話最為流行，其衍生而來的現代標準漢語（中華人民共和國的普通話、中華民國的國語、以及新加坡的標準華語）是大中華區的主要通用語。此外，漢語還是聯合國正式語文[5]，並被上海合作組織等國際組織採用為官方語言。國際上常將「漢語」稱為「中文」，這是因為其他國家（除日本外）均使用表音文字，對於「文」[6]與「語」[7]並不作區分，不符合漢語語法；然而華人使用表意文字，文字[8]並不等於語言[9]，作為母語人士不宜隨之誤用。[註 1]

對於漢語下屬語言的分類，學界主要有兩種觀點，一種觀點將漢語定義為語言，並將官話、贛語、閩語、粵語、客家話、吳語、湘語七大分支定義為一級方言；另一種觀點則將漢語視為語族，七大分支因無法互相溝通而視為語支，而語支下面的各個分支被視為獨立的語言[10]，如國際標準化組織就將漢語族分為13種語言：閩東語、晉語、官話、莆仙語、徽語、閩中語、贛語、客家話、湘語、閩北語、閩南語、吳語、粵語。無論用哪種觀點，上述各種語言都是平等的，它們都是漢語裡的一分子；而漢語是它們的集合體，並非專指它們當中的其中一種。

漢語使用的文字是漢字，以漢字寫成的詞、詞組、句子、段落、文字作品，稱為中文（又稱華文、國文、漢文、唐文）。漢字是一種意音文字，表意之同時也具一定表音功能；而漢語屬分析語，且聲調辨義。

漢語包含書面語及口語兩部分，古代書面語稱為文言文，現代書面語一般指官話白話文，即使用標準官話文法、詞彙的中文通行文體。粵港澳等地又流行夾雜文言文、官話白話文及粵語白話文的三及第文體，吳語區亦偶有人書寫吳語白話文。漢字也被其他語言使用，並形成漢字文化圈。'''
ENCODING_HRV = '''Hrvatski jezik (ISO 639-3: hrv) skupni je naziv za nacionalni standardni jezik Hrvata, te za skup narječja i govora kojima govore ili su nekada govorili Hrvati. Njime govori više od 5,5 milijuna ljudi[2], poglavito Hrvata u Hrvatskoj (3 980 000; popis iz 2001.) i Bosni i Hercegovini (469 000; 2004.).[3] Hrvatski je materinski jezik za Hrvate u drugim zemljama; Sjedinjenim Američkim Državama (58 400; popis iz 2000.);[1] Austriji, 19 400 (popis iz 2001.); Srbiji 19 223 popis 2011.  Inačica izvorne stranice arhivirana 4. ožujka 2022.; Mađarskoj, (14 300; popis iz 2001.); Italiji (3500; Vincent 1987.); Crnoj Gori (6810; 2006.); Slovačkoj, 890; popis iz 2001.).


nastanak upitno-odnosnih zamjenica u hr. jeziku

hrvatski dijalekti dijagram međusobnih odnosa

hrvatski dijalekti pojednostavljen dijagram međusobnih odnosa

Pojednostavljena pravila kategorizacije hrvatskih dijalekata

Sveukupna pravila kategorizacije hrvatskih dijalekata

Osnovna obilježja hr.narječja

Razvoj hrvatskih govora po refleksu jata i šćakavskoj isoglosi

Pojednostavljeni prikaz razvitka hrvatskih dijalekata

Usporedba hr.narječja
Hrvatski je službeni jezik Republike Hrvatske te jedan od tri službena jezika Bosne i Hercegovine; također je jedan od 24 službena jezika Europske unije.[2]

Kao manjinski hrvatski jezik je u službenoj uporabi u nekim pokrajinama na ozemlju susjednih zemalja, tako je hrvatski jedan od službenih jezika u uporabi u crnogorskim općinama u Boki kotorskoj, zatim jedan je od sedam službenih jezika u srbijanskoj autonomnoj pokrajini Vojvodini,[4] lokalni idiomi hrvatskoga jezika u službenoj su uporabi u austrijskoj saveznoj zemlji Gradišću, te također u talijanskoj provinciji Moliseu i rumunjskoj županiji Karaš-Severin.

Hrvatski jezik obuhvaća standardni, odnosno književni ili opći hrvatski jezik te sve narodne govore kojima se služe Hrvati.[3]

U genetsko-lingvističkom smislu hrvatski jezik je sustav triju narječja:

štokavskog
kajkavskog
čakavskog
Makar je standardni hrvatski jezik očito najbliži štokavskom narječju, i preostala dva narječja su mnogo doprinijela njegovu formiranju, te jezikoslovac Radoslav Katičić i književnik Drago Štambuk promoviraju gledište da se hrvatski jezik uopće ne može sagledati izvan tog suodnosa njegovih triju narječja, koji nazivaju "zlatnom formulom hrvatskoga jezika ča-kaj-što".[5] Drago Štambuk se, konstatirajući da je hrvatski standard nastao uz jak doprinos sva tri hrvatska narječja, zalaže za (ponovno, i jače) "otvaranje prozorčića" na suvremenom književnom standardu, kako bi se omogućilo da ga dodatno "bogati i oplemenjuje leksik iz čakavice, kajkavice i dijalektalnih varijanti štokavice. Enormna je leksička pričuva hrvatskoga jezika, tolika da je hrvatski jezik kroz nju jedan od najbogatijih slavenskih jezika."[6]

Nazivi narječja potječu od arhaičnog oblika odnosno-upitne zamjenice koja je glasila kъ, a kasnije je prešla u čь (ь i ъ oznake su za poluglase). U čakavskom se poluglas vokalizirao i prešao u a (a javljaju se i druge kombinacije če, ca, ce, ća, će...), u štokavskom se zamjenica čь povezala s to, čьto. Kasnije je polugas iščezao ostavivši čto, koje je zbog pojednostavnjivanja prešlo u što (a javljaju se i druge kombinacije šta, št'a, śta, što, št'o, śto...). U kajkavskom se arhaični oblik zamjenice kъ kombinirao s jь, pa je prelaskom u a prvog, a gubljenjem drugog poluglasa nastao kaj  (a javljaju se i druge kombinacije kej, ke, ka...).

Zanimljivost je da se slična, štokavska promjena, dogodila i u ruskom jeziku, no dok oni izgovaraju što, u pismu im je ostao arhaizam čto.

Najstariju gramatika hrvatskog književnog jezika napisao je isusovac Bartol Kašić početkom 17. stoljeća: knjiga je objavljena u Rimu 1604. godine (tj. nedugo nakon prve gramatike engleskog jezika koju je William Bullokar objavio 1586. godine, te približno stoljeće i pol prije prvih gramatika ruskog jezika) pod imenom Institutionum linguae illyricae (Ustroj ilirskoga/hrvatskoga jezika): oslanjajući se na stoljetnu tradiciju hrvatskog pisanja na sva tri narječja, on se većinom oslanja na novoštokavsku jekavicu (koju zove "dubrovačkim" govorom) na koju 1630.-ih godina prevodi Bibliju, te u ono doba po hrvatskim zemljama znatno raširenije štokavske ikavice (koju Kašić zove "bosanskim" govorom), kojom piše svoj Ritual Rimski (službena zbirka tekstova i uputa za bogoslužje) iz 1640. godine.

Nakon što se tijekom narednih stoljeća brojna književna djela – pa i gramatike – pišu kako na novoštokavskoj ikavici, tako i na ijekavici[7] (također i na čakavskom, te osobito kajkavskom narječju), zaslugom Ilirskog pokreta sredinom 19. stoljeća sve više prevladava ijekavica; naposljetku krajem 19. stoljeća postaje za uporabu u školama obvezatan Hrvatski pravopis Ivana Broza iz 1892. godine, koji upućuje na službenu upotrebu jekavske novoštokavice kakvu se – uz manje promjene – kao standardni hrvatski jezik koristi do danas.

Do najnovijeg vremena, najveći dio hrvatskih govornika je izvan službenih prigoda govorio jednim od narječja hrvatskog jezika, koji se i danas puno koriste, osobito u ruralnim područjima. Standardni jezik koji se sve više upotrebljava kao govorni jezik u urbanim područjima, ima često regionalne posebnosti, koje u pravilu dolaze iz lokalnih dijalekata.

Dijalektima čakavskoga i kajkavskoga narječja govore samo Hrvati (na južnoslavenskom dijalektalnom kontinuumu, možemo prepoznati srodnost hrvatskih kajkavskih govora s nekim slovenskim narječjima, napose s govorima Slovenaca uz granicu s Hrvatskom, pogotovo na područjima koja su nekoć crkveno ili upravno pripadala Hrvatskoj), dok se štokavskim narječjem uz Hrvate služe i Bošnjaci, Srbi te Crnogorci.

Od štokavskih dijalekata Hrvati se u načelu služe sa sva četiri podrijetlom zapadnoštokavska dijalekta, a to su sjeverni (slavonski) dijalekt kojim govore samo Hrvati, zapadni (novoštokavska ikavica) dijalekt kojim većinom govore Hrvati i ponešto Bošnjaci u zapadnoj Bosni, istočni (istočnobosanski) dijalekt kojim se služe Hrvati i Bošnjaci te južni (novoštokavska jekavica) dijalekt koji rabe Hrvati na više terena i osobito na širem dubrovačkome području, ali i drugi južnoslavenski narodi koji se služe sličnim ijekavskim poddijalektima.[3]

Granični dijalekti kajkavskog narječja; Donjosutlanski, Goranski i Prigorski posjeduju vezu ili prijelaz prema čakavštini, a jugoistočna podgrupa čakavskog narječja; južnočakavski, lastovski i jugozapadni istarski posjeduje vezu ili prijelaz prema (zapadnoj) štokavštini, dok sjeverozapadna (sjevernočakavski i buzetski) i središnja podgrupa (srednječakavski) dijeli više isoglosa s kajkavštinom.

Šćakavski dijelekti (slavonski i istočnobosanski), djele niz sličnosti s čakavštinom, dok sjever slavonskog posjeduje i prijelaz prema kajkavskim govorima. Novoštokavski dijalekti (zapadni i južni) dijele pojedine isoglose s južnom podgrupom čakavskog narječja.

Više informacija o narječjima i njihovom razvitku se može naći ovdje.

Hrvatske manjinske zajednice
Hrvati u Gradišću (Austrija, Mađarska, Slovačka, Češka) služe se najviše dijalektima čakavskoga narječja u središnjem Gradišću, zatim štokavskoga narječja u južnom Gradišću i kajkavskoga narječja u sjevernom Gradišću, no oni rabe vlastiti zajednički standardizirani oblik gradišćanskohrvatskoga mikrojezika. Hrvati u talijanskoj pokrajini Molise služe se štokavsko-čakavskim narječjem, a Hrvati Krašovani u Rumunjskoj pod utjecajem okoline razvili su jedan specifičan karaševski govor koji danas po svojim svojstvima spada pod torlačko narječje (neekavsko, jer pod akcentom imaju zatvoreno e od jata, izvan akcenta i)[8]), (u Rekašu na rumunjsko-srbijanskoj granici Hrvatska manjina rabi – kosovsko–resavski dijalekt odnosno rekaške govore, Hrvati po istočnom Srijemu služe se vojvođanskim dijalektom ili iločkim dijalektom, a Hrvati u Boki kotorskoj zetsko–južnosandžačkim ili bokeljsko-perojskim, Hrvati koji obitavaju na Kosovu u Janjevu i Letnici razvili su govore torlačkoga narječja, odnosno Janjevačko-lepenički dijalekt.[9] Svi ti dijalekti pripadaju srednjojužnoslavenskom dijasustavu slavenske jezične grane.[10]

Znanost koja se bavi hrvatskim jezikom zove se kroatistika.

Vidi: Gramatika, Pravopis'''
ENCODING_DAN = '''Bokmål er en varietet av norsk skriftspråk. Bokmål er en av to offisielle målformer av norsk skriftspråk, hvorav den andre er nynorsk. I skrift har 87,3% bokmål som hovedmål i skolen.[1] Etter skriftreformene av riksmål i 1987 og bokmål i 1981 og 2005 er det lite som skiller bokmål og riksmål i alminnelig bruk.

Det har blitt anslått at mer enn 20 % av befolkningen i Norge snakker såkalt standard østnorsk, den alminnelige formen av talt bokmål på Østlandet.[2][3] Det er også sosiolekter i andre deler av landet som anses som talemålsvarianter av bokmål, mest kjent er såkalt «fintrønder» i Trondheim[4] og «penbergensk» i Bergen.'''
ENCODING_ENG = '''English is a West Germanic language in the Indo-European language family, with its earliest forms spoken by the inhabitants of early medieval England.[3][4][5] It is named after the Angles, one of the ancient Germanic peoples that migrated to the island of Great Britain. Existing on a dialect continuum with Scots, and then most closely related to the Low German and Frisian languages, English is genealogically Germanic. However, its vocabulary also shows major influences from French (about 28% of Modern English words) and Latin (also about 28%),[6] plus some grammar and a small amount of core vocabulary influenced by Old Norse (a North Germanic language).[7][8][9] Speakers of English are called Anglophones.

The earliest forms of English, collectively known as Old English, evolved from a group of North Sea Germanic dialects brought to Great Britain by Anglo-Saxon settlers in the 5th century and further mutated by Norse-speaking Viking settlers starting in the 8th and 9th centuries. Middle English began in the late 11th century after the Norman Conquest of England, when considerable Old French (especially Old Norman French) and Latin-derived vocabulary was incorporated into English over some three hundred years.[10][11] Early Modern English began in the late 15th century with the start of the Great Vowel Shift and the Renaissance trend of borrowing further Latin and Greek words and roots into English, concurrent with the introduction of the printing press to London. This era notably culminated in the King James Bible and plays of William Shakespeare.[12][13]

Modern English grammar is the result of a gradual change from a typical Indo-European dependent-marking pattern, with a rich inflectional morphology and relatively free word order, to a mostly analytic pattern with little inflection, and a fairly fixed subject–verb–object word order.[14] Modern English relies more on auxiliary verbs and word order for the expression of complex tenses, aspect and mood, as well as passive constructions, interrogatives and some negation.

Modern English has spread around the world since the 17th century as a consequence of the worldwide influence of the British Empire and the United States of America. Through all types of printed and electronic media of these countries, English has become the leading language of international discourse and the lingua franca in many regions and professional contexts such as science, navigation and law.[3] English is the most spoken language in the world[15] and the third-most spoken native language in the world, after Standard Chinese and Spanish.[16] It is the most widely learned second language and is either the official language or one of the official languages in 59 sovereign states. There are more people who have learned English as a second language than there are native speakers. As of 2005, it was estimated that there were over 2 billion speakers of English.[17] English is the majority native language in the United Kingdom, the United States, Canada, Australia, New Zealand and the Republic of Ireland (see Anglosphere), and is widely spoken in some areas of the Caribbean, Africa, South Asia, Southeast Asia, and Oceania.[18] It is a co-official language of the United Nations, the European Union and many other world and regional international organisations. English accounts for at least 70% of speakers of the Germanic language branch of Indo-European.'''
ENCODING_EST = '''Eesti keel (varasem nimetus maakeel) on läänemeresoome lõunarühma kuuluv keel.

Eesti keel on Eesti riigikeel ja 2004. aastast ka üks Euroopa Liidu ametlikke keeli.

2012. aasta seisuga kõneles eesti keelt emakeelena umbes 922 000 inimest Eestis ja 160 000 mujal maailmas ning võõrkeelena 168 000 inimest.[1]

Eesti keelel on kaks suuremat murderühma (põhjaeesti ja lõunaeesti), mõnes käsitluses eristatakse ka kirderanniku murdeid eraldi murderühmana. Liikumisvõimaluste laienemine ning põhjaeesti keskmurde alusel loodud normitud eesti kirjakeele kasutus on põhjustanud murdeerinevuste taandumise.

Nelja piirkondliku põhivariandiga lõunaeesti murderühma käsitletakse vahel ka eraldi lõunaeesti keelena. Lõunaeesti keele suurima kõnelejate arvuga võru murret ehk võru keelt käsitletakse vahel samuti omaette keelena. Setu keelt peetakse enamasti aga võru keele variandiks.

Eesti keele harukordsusi on hääliku kolm pikkusastet: lühike, pikk ja ülipikk. Eri pikkusaste võib anda sõnale eri vormi või tähenduse – näiteks /linn/, /linˑa/ (omastav kääne) ja /lin:a/ (sisseütlev kääne); või /vala/ (käskiv kõneviis sõnast valama), /vaˑla/ (omastav kääne sõnast vaal) ja /vaːla/ (osastav kääne sõnast vaal).[viide?]

Võrdlevgrammatiliste uurimuste järgi on eesti keel maailma keerukamaid keeli.[2]

Eesti keelt uuritakse Eesti Keele Instituudis, Tartu Ülikoolis, Tallinna Ülikoolis ja veel mitmes teadusasutuses mujal maailmas.

Eesti keel on Internetis levikult 39. kohal, 2019. aasta seisuga oli 0,1% veebisaite eestikeelsed.[3] Eestikeelne Vikipeedia oli sel aastal artiklite arvult 45. kohal[4].'''
ENCODING_FRA = '''Le français est une langue indo-européenne de la famille des langues romanes dont les locuteurs sont appelés francophones, également surnommé la langue de Molière.

Le français est parlé, en 2023, sur tous les continents par environ 321 millions de personnes5,2 : 235 millions l'emploient quotidiennement, et 90 millions3 en sont des locuteurs natifs. En 2018, 80 millions d'élèves et étudiants s'instruisent en français dans le monde6. Selon l'Organisation internationale de la francophonie (OIF), il pourrait y avoir 700 millions de francophones sur Terre en 20507.

Le français est la cinquième langue la plus parlée au monde après l'anglais, le mandarin, l'hindi et l’espagnol8. Elle est également la deuxième langue la plus apprise sur le globe, la troisième langue des affaires et du commerce, la quatrième langue employée sur Internet9.

Dans le monde, 29 États ont le français comme langue officielle. C'est une des six langues officielles ainsi qu'une des deux langues de travail de l'Organisation des Nations unies. Le français est une langue officielle ou de travail de nombreuses organisations gouvernementales internationales, parmi lesquelles l'Union postale universelle ou les trois autorités mondiales de régulation du système métrique. Il est aussi langue officielle ou de travail de nombreuses organisations gouvernementales régionales, telles que l'Union africaine ou l’Union européenne, et est aussi langue officielle ou de travail de nombreuses organisations non gouvernementales internationales, comme le Comité international olympique ou le Mouvement international de la Croix-Rouge et du Croissant-Rouge.

L'histoire du français et des francophones est celle de la rencontre et de l'échange entre de nombreux peuples. Le français est une variété de la langue d'oïl, un groupe de langues romanes parlées originellement dans la partie septentrionale du domaine gallo-roman, sur le territoire des actuelles France, Suisse et Belgique. Les langues gallo-romanes résultent de l'évolution, sous l'influence de langues germaniques, tel que le vieux-francique des Francs, du latin populaire parlé en Gaule par les Gallo-Romains. Ces derniers formaient un ensemble de peuples d'origines principalement celtes qui furent progressivement romanisés à la suite de la conquête romaine de la région, terminée aux alentours de 52 av. J.-C. En 843, l'historien franc Nithard, petit-fils de Charlemagne, produit ce qui est considéré comme le premier texte connu en langue française. Il s'agit d'une chronique qui retranscrit les serments d'alliance, prononcés à Strasbourg l'année précédente, par Louis le Germanique, premier souverain allemand.

Durant le Moyen Âge européen, en particulier entre le xe et le xiiie siècle, alors que le système de déclinaisons de l'ancien français s'effondre, les langues d'oïl commencent à se diffuser hors de leur domaine d'origine du fait des invasions normandes des îles Britanniques, du sud de l'Italie ou bien des croisades qui, en établissant des États latins au Levant, font du français une base de la lingua franca méditerranéenne. En 1539, par l’ordonnance de Villers-Cotterêts, le moyen français, langue maternelle des dynasties capétiennes, devient une langue juridique et administrative en France. À la même période, il commence à se diffuser plus massivement hors d'Europe, d'abord en Amérique, puis en Afrique, en Asie et en Océanie, sous l'effet de l'expansion des empires coloniaux français puis belge. À partir du dix-septième siècle, dans les océans Atlantique, Indien et Pacifique, les déportations de populations pratiquées par les empires européens vers leurs colonies amènent, dans un contexte principalement d'esclavage, à la formation de nombreux créoles à base lexicale française. En 1794, par le décret révolutionnaire du 2 thermidor an II et malgré le fait qu'il ait été, sous l'Ancien Régime, la langue des cours royales et princières européennes, le français classique, langue des Lumières, devient la seule langue officielle de la Première République française10. Une des particularités du français se trouve dans le fait que son développement et sa codification ont été en partie l'œuvre de groupes intellectuels, comme la Pléiade, ou d'institutions, comme l'Académie française. Le français est ainsi souvent considéré comme une langue « académique ». À partir du dix-neuvième siècle, et malgré quelques réformes au cours des siècles suivants, son orthographe codifiée commence à se figer. Elle est considérée comme transparente dans le sens de la lecture, mais opaque dans le sens de l'écriture. Au cours du xxe siècle, le français devient une langue d'envergure mondiale en même temps qu'il s'émancipe de l'Europe : à partir de ce siècle le nombre de francophones vivant hors d'Europe dépasse le nombre de locuteurs sur le continent d'origine de la langue.

Entre le 16 mars et le 20 mars 1970 et sous l'impulsion de ceux qui deviendront les « cinq pères fondateurs de la Francophonie » — Léopold Sédar Senghor, poète, écrivain et premier président de la république du Sénégal, Habib Bourguiba, avocat et premier président de la République tunisienne, Hamani Diori, professeur et premier président de la république du Niger, Norodom Sihanouk, roi du Cambodge et Jean-Marc Léger, écrivain et journaliste canadien — a lieu, dans la salle des séances de l'Assemblée nationale du Niger, la conférence de Niamey. Celle-ci, une des premières conférences réunissant les gouvernements des états francophones, établit l'Agence de coopération culturelle et technique, le premier organisme intergouvernemental francophone, et jette ainsi les bases pour la création d'une Organisation internationale de la francophonie (OIF) qui réunirait les peuples partageant la langue française. En commémoration de cet évènement, les états membres de l'Organisation font en 1988 du 20 mars la Journée internationale de la francophonie. En 1989, ont lieu au Maroc les premiers jeux de la Francophonie qui réunissent pour la première fois les athlètes de la communauté francophone autour de la langue qu'ils partagent. En 1997, à Hanoï, capitale du Viêt nam, les États francophones adoptent la Charte institutionnelle de la Francophonie qui sera complétée en 2005 à Antananarivo, capitale de Madagascar, par la Charte de la Francophonie. Ces deux chartes présentent l'importance du multilinguisme pour le monde francophone, les valeurs de solidarité, d'égalité et de fraternité entre les peuples qui doivent être véhiculées par la langue française, vecteur de progrès et de modernité, ainsi que le rôle actif que doivent exercer les francophones pour la préservation de la diversité linguistique et culturelle. En 2010, l'Organisation des Nations unies déclare que le 20 mars de chaque année sera observée à travers le monde la Journée de la langue française en souvenir de la conférence de Niamey. Les organisations francophones proposent autour de cette date des semaines d'échanges et de discussions souvent appelées semaines de la langue française et de la francophonie.

La langue française est un attribut culturel souverain pour de nombreux peuples et États comme en France où depuis 1992 « la langue de la République est le français » ou au Québec où depuis 1977 elle « permet au peuple québécois d’exprimer son identité ». Elle est également le principal véhicule des cultures francophones dans le monde et le moyen principal d'expression de leurs pensées. La langue, parfois surnommée « langue de Molière11 », ne cesse de s'enrichir que ce soit de façon formelle, par des décrets par exemple, mais aussi de façon informelle.

Le français est la deuxième langue parmi les langues étrangères le plus fréquemment enseignées à travers le monde, y compris aux États-Unis7. Il est également la quatrième langue la plus utilisée sur internet après l'espagnol, le mandarin et l'anglais12, langue dont le vocabulaire a été fortement enrichi par le français. L'édition francophone de Wikipédia est la 5e au monde en nombre d'articles et la 3e en nombre d'utilisateurs.'''
ENCODING_DEU = '''Die deutsche Sprache bzw. Deutsch ([dɔɪ̯tʃ];[26] abgekürzt dt.) ist eine westgermanische Sprache, die weltweit etwa 90 bis 105 Millionen Menschen als Muttersprache und weiteren rund 80 Millionen als Zweit- oder Fremdsprache dient.

Das Deutsche ist eine plurizentrische Sprache, enthält also mehrere Standardvarietäten in verschiedenen Regionen. Ihr Sprachgebiet umfasst Deutschland, Österreich, die Deutschschweiz, Liechtenstein, Luxemburg, Ostbelgien, Südtirol, das Elsass und Lothringen sowie Nordschleswig. Außerdem ist Deutsch eine Minderheitensprache in einigen europäischen und außereuropäischen Ländern, z. B. in Rumänien und Südafrika sowie Nationalsprache im afrikanischen Namibia. Deutsch ist die meistgesprochene Muttersprache in der Europäischen Union (EU).[27]

Ursprünglich bestand der deutsche Sprachraum aus einer Vielzahl von Mundarten innerhalb eines Dialektkontinuums, das sich aufgrund der zweiten (hochdeutschen) Lautverschiebung in hochdeutsche (oberdeutsche und mitteldeutsche) und niederdeutsche Mundarten einteilen lässt. (Die Niederdeutsche Sprache ist also oft nicht mitgemeint, wenn von „der deutschen Sprache“ die Rede ist.)

Die Standardsprache mit ihren Standardvarietäten, Deutsch oder Hochdeutsch genannt, ist das Ergebnis bewusster sprachplanerischer Eingriffe. Das Standarddeutsche überspannt als Dachsprache den Großteil der Mundarten des Dialektkontinuums.

Die Germanistik erforscht, dokumentiert und vermittelt die deutsche Sprache und Literatur in ihren historischen und gegenwärtigen Formen. Die deutsche Gegenwartssprache umfasst einer neueren Untersuchung nach mehr als fünf Millionen Wörter, fast ein Drittel mehr als noch vor 100 Jahren.[28]'''
ENCODING_ELL = '''Η ελληνική γλώσσα ανήκει στην ινδοευρωπαϊκή οικογένεια[9] και αποτελεί το μοναδικό μέλος του ελληνικού κλάδου, ενώ είναι η επίσημη γλώσσα της Ελλάδας και της Κύπρου. Ανήκει επίσης στο βαλκανικό γλωσσικό δεσμό. Στην ελληνική γλώσσα, έχουμε γραπτά κείμενα ήδη από τον 15ο αιώνα π.Χ.. Σαν Παγκόσμια Ημέρα Ελληνικής Γλώσσας, κάθε έτος, έχει καθιερωθεί η 9η Φεβρουαρίου. Έχει την μακροβιότερη καταγεγραμμένη ιστορία από οποιαδήποτε άλλη ζωντανή ινδοευρωπαϊκή γλώσσα με τουλάχιστον 3.400 χρόνια γραπτής ιστορίας.[10] Γράφεται με το ελληνικό αλφάβητο το οποίο χρησιμοποιείται για περίπου 2.600 χρόνια.[11][12] Προηγουμένως η ελληνική γλώσσα γραφόταν με τη Γραμμική Β και το κυπριακό συλλαβάριο.[13] Το ελληνικό αλφάβητο προέρχεται από το φοινικικό αλφάβητο. Στο ελληνικό αλφάβητο βασίζεται το λατινικό, το κυριλλικό, το αρμενικό, το κοπτικό, το γοτθικό και πολλά άλλα αλφάβητα.

Η ελληνική γλώσσα κατέχει υψηλή -ιστορική- θέση στην ιστορία του Δυτικού κόσμου.[14] Ξεκινώντας με τα Ομηρικά έπη, η αρχαία ελληνική λογοτεχνία περιλαμβάνει πολλά σημαντικά έργα της Ευρωπαϊκής λογοτεχνίας. Η ελληνική γλώσσα είναι η γλώσσα με την οποία συντέθηκαν πολλά από τα θεμελιώδη επιστημονικά και φιλοσοφικά κείμενα. Η Καινή Διαθήκη γράφτηκε στα ελληνικά και έπειτα μεταφράστηκε σε άλλες γλώσσες.[15][16] Μαζί με τα λατινικά κείμενα και τις παραδόσεις του Ρωμαϊκού κόσμου, τα ελληνικά κείμενα και η ελληνική κοινωνία της αρχαιότητας αποτελούν μέρος της κλασικής επιστήμης.

Κατά τη διάρκεια της αρχαιότητας, η ελληνική ήταν η κύρια γλώσσα του μεσογειακού κόσμου. Έγινε έπειτα η επίσημη γλώσσα της Βυζαντινής Αυτοκρατορίας και εξελίχθηκε στα Μεσαιωνικά Ελληνικά.[17] Στη σύγχρονη μορφή της τα ελληνικά είναι η επίσημη γλώσσα της Ελλάδας και της Κύπρου και μια από τις 24 επίσημες γλώσσες της Ευρωπαϊκής Ένωσης. Την ομιλούν, ως μητρική γλώσσα, τουλάχιστον 13,5 εκατομμύρια άνθρωποι στην Ελλάδα, την Κύπρο, την Ιταλία, την Αλβανία, την Τουρκία και την ελληνική διασπορά. Επίσης εκατομμύρια άτομα γνωρίζουν ελληνικά, είτε την αρχαία μορφή της ή τα νέα ελληνικά.

Οι ελληνικές ρίζες χρησιμοποιούνται για αιώνες και συνεχίζουν να χρησιμοποιούνται ευρέως για να σχηματίσουν νέες λέξεις σε άλλες γλώσσες. Πολλές ελληνικές λέξεις μπορούν να εντοπιστούν στις περισσότερες κύριες γλώσσες του κόσμου. Τα ελληνικά και τα λατινικά, ως γλωσσικές δεξαμένες, είναι οι κύριες πηγές του διεθνούς επιστημονικού και τεχνολογικού λεξιλογίου.

Ο συνολικός αριθμός των ανθρώπων που μιλούν τα νέα ελληνικά ως μητρική τους γλώσσα είναι περίπου 14 εκατομμύρια άτομα. Οι περισσότεροι από αυτούς είναι Έλληνες στην εθνικότητα, αν και στην Ελλάδα χρησιμοποιείται επίσης ευρέως από αρκετούς εξελληνισμένους Αρωμάνους, Μεγλενορουμάνους, Τσιγγάνους, Αλβανούς (ιδιαίτερα Αρβανίτες), Σλάβους και μια σειρά από μουσουλμανικές εθνότητες στα βόρεια της χώρας. Χάρη στους αυξημένους οικονομικούς δεσμούς της Ελλάδας με άλλες βαλκανικές χώρες, καθώς και χάρη στις μαζικές μεταναστεύσεις προς την Ελλάδα και την Κύπρο τα τελευταία είκοσι χρόνια, ένας σημαντικός αριθμός κατοίκων στις χώρες που συνορεύουν με την Ελλάδα μιλάει και ελληνικά. Ελληνόγλωσσοι υπάρχουν πάρα πολλοί στην Αλβανία, όπου ομιλείται ευρέως στα νότια της χώρας και στις μεγάλες πόλεις και είναι ουσιαστικά η γλώσσα εργασίας σε τρεις δήμους της Αλβανίας. Ως σημαντική γλώσσα της διασποράς, τα ελληνικά χρησιμοποιούνται μεταξύ των Ελλήνων της Αυστραλίας, του Καναδά και των ΗΠΑ. Ο συνολικός αριθμός των ανθρώπων που μιλούν την ελληνική ως ξένη γλώσσα κυμαίνεται στα 3 με 5 εκατομμύρια άτομα.

Η ελληνική λογοτεχνία έχει πλούσια παραγωγή σε όλα τα στάδια της ιστορίας της. Στη Ρωμαϊκή Αυτοκρατορία η γνώση της ελληνικής γλώσσας θεωρούνταν υποχρέωση του κάθε μορφωμένου Ρωμαίου. Τα λατινικά έχουν δανειστεί μεγάλο αριθμό ελληνικών δανείων και αντιθέτως ελληνικά έχουν σημαντικό αριθμό λατινικών και ρομανικών λέξεων.'''
ENCODING_HEB = '''שם השפה עברית פירושה "לשונו של עֵבֶר",[2] ונגזר מהשם של הדמות המקראית עֵבֶר, אביהם הקדמון של עמים רבים, בהם עם ישראל. לפי המסורת היהודית,[3] עבר סירב לקחת חלק בבניית מגדל בבל, ועל כן הוא וצאצאיו לא נענשו על בניית המגדל, ושפתם לא נתבלבלה. עבר שימר את השפה האוניברסלית המקורית - העברית.
...אבל אברהם אבינו עצמו היה בדור הָפַּלָּגָה ונשאר הוא וקרוביו בלשון עֵבֶר, אבי אביו, ולזה נקרא עִבְרִי... ...כי כל הלשונות אשר היו לפניהם חמש מאות שנה היו לשון עבר לבדה ונפלגה בבבל בימי פֶּלֶג... 

— רבי יהודה הלוי, ספר הכוזרי, פרק א, סעיף מט
[4]

המושג "עברי" נזכר שלושים וארבע פעמים בתנ"ך ככינוי לבני ישראל, אולם לא כשפה.[5] במקרא, שמה של שפתם של העברים מכונה "יהודית",[6] וגם בשם "שפת כנען".[7] ייתכן שהשם 'יהודית' היה רק שם הניב שדובר בממלכת יהודה או באזור ירושלים, להבדיל מהניב של ממלכת הצפון, ממלכת ישראל (אם כי גם לפי תאוריה זו, מדובר בסך הכול בשני ניבים שונים של אותה שפה, ולא בשתי שפות שונות).

המקור הקדום ביותר המזכיר את המונח עברית כשם השפה, הוא מקור יווני מן המאה ה-2 לפנה"ס.[8] המקור הוא נכדו של בן סירא שכותב בהקדמה לתרגום החיבור של סבו ליוונית שבוצע על ידיו כי:
לכן מתבקשים אתם לקרא את הקריאה ברצון ובתשומת לב, ולסלוח אם נראה שלא הצלחנו במילים ידועות שעמלנו באהבה לתרגם אותן, כי הנאמרים בעברית אין כחם שווה כשהם מועתקים ללשון אחרת. 

— משה צבי סגל, ספר בן סירא השלם, עמ' א. לנוסח המקור ביוונית ראו כאן
בלשון חז"ל שדוברה החל מהמאה הראשונה לספירה, הכינוי המקובל לשפה המקראית ולשפה המדוברת היה "לשון הקודש",[9] והמונח "עברית" שימש לציון הכתב העברי הקדום,[10] וכן לציון שפתם של בני עבר הנהר,[11] אך יש גם שימושים במונח "עברית" המתייחסים ללשון המקרא.[12]

הניב התנ"כי מכונה "לשון המקרא", כדי להבדילו מלשון חז"ל המכונה גם "לשון חכמים", שהיא בעצם ניב מאוחר של עברית.

בברית החדשה משמש המונח "עברית" כשם לשפה הארמית שדוברה על ידי ה"עבריים" (תושבי עבר הנהר) בארץ ישראל, אולם בספרות חז"ל משמש מונח זה רק לעברית (המשנאית).[13]'''
ENCODING_ISL = '''Íslenska er vesturnorrænt, germanskt og indóevrópskt tungumál sem er einkum talað og ritað á Íslandi og er móðurmál langflestra Íslendinga.[5] Það hefur tekið minni breytingum frá fornnorrænu en önnur norræn mál[5] og er skyldara norsku og færeysku en sænsku og dönsku.[2][3]

Ólík mörgum öðrum vesturevrópskum tungumálum hefur íslenskan ítarlegt beygingarkerfi. Nafnorð og lýsingarorð eru beygð jafnt sem sagnir. Fjögur föll eru í íslensku, eins og í þýsku, en íslenskar nafnorðsbeygingar eru flóknari en þær þýsku. Beygingarkerfið hefur ekki breyst mikið frá víkingaöld, þegar Norðmenn komu til Íslands með norræna tungumál sitt.

Meirihluti íslenskumælenda býr á Íslandi, eða um 300.000 manns.[1] Um 8.000 íslenskumælendur búa í Danmörku, en þar af eru 3.000 nemendur. Í Bandaríkjunum eru talendur málsins um 5.000, og í Kanada 1.400. Stærsti hópur kanadískra íslenskumælenda býr í Manitoba, sérstaklega í Gimli, þar sem Vestur-Íslendingar settust að. Þó að 97% Íslendinga telji íslensku móðurmál sitt er tungumálið nokkuð í rénun utan Íslands. Þeir sem tala íslensku utan Íslands eru oftast aðfluttir Íslendingar, nema í Gimli þar sem íslenskumælendur hafa búið frá 1880.

Árnastofnun sér um varðveislu málsins og hýsir miðaldahandrit sem skrifuð voru á Íslandi. Auk þess styður hún rannsóknir á málinu. Frá 1995 hefur verið haldið upp á dag íslenskrar tungu þann 16. nóvember á hverju ári, sem var fæðingardagur Jónas Hallgrímssonar skálds.'''
ENCODING_GLE = '''Is ceann de na teangacha Ceilteacha í an Ghaeilge (nó Gaeilge na hÉireann mar a thugtar uirthi corruair), agus ceann de na trí cinn de theangacha Ceilteacha ar a dtugtar na teangacha Gaelacha (Gaeilge, Gaeilge Mhanann agus Gaeilge na hAlban) go háirithe. Labhraítear in Éirinn go príomha í, ach tá cainteoirí Gaeilge ina gcónaí in áiteanna eile ar fud an domhain.

Is í an teanga náisiúnta nó dhúchais agus an phríomhtheanga oifigiúil i bPoblacht na hÉireann í an Ghaeilge. Tá an Béarla luaite sa Bhunreacht mar theanga oifigiúil eile. Tá aitheantas oifigiúil aici chomh maith i dTuaisceart Éireann, ar cuid den Ríocht Aontaithe é. Ar an 13 Meitheamh 2005 d'aontaigh airí gnóthaí eachtracha an Aontais Eorpaigh glacadh leis an nGaeilge mar theanga oifigiúil oibre san AE. Ón 1 Eanáir 2007 cuireadh tús leis an stádas oifigiúil seo, agus ba é an tAire Nollaig Ó Treasaigh, T. D., an chéad aire Éireannach a labhair Gaeilge ag cruinniú de chuid Chomhairle na nAirí, an 22 Eanáir 2007.

Tá go leor ainmneacha eile réigiúnda nó stairiúla ar an teanga freisin: Gaedhealg, Gaedhilge agus Gaedhilg (i gConamara); Gaedhilic, Gaeilic agus Gaeilig (in áiteanna i gCúige Uladh agus Maigh Eo); Gaedhealaing, Gaoluinn agus Gaeilinn (i bPort Láirge); Gaelainn (sa Mhumhain); Gaedhlag (Ó Méith, Ard Mhacha agus Lú); agus Guithealg nó Goidelc (sa tSean-Ghaeilge). Go minic, níl i gceist leo seo ach litrithe malartacha ar an bhfocal "Gaeilge" agus iad ag baint leis an tréimhse réamhchaighdeánach (féach thíos chun a thuilleadh eolais a fháil), ach tabhair faoi deara gurb iondúil inniu a úsáidtear an leagan Muimhneach d'ainm na teanga, Gaelainn, le tagairt a dhéanamh do chanúint an chúige ina gcluinfeá an t-ainm seo uirthi. D'fheicfeá Gaoluinn, leis, toisc gur mar é fada a fhuaimnítear ao an litrithe sna canúintí deisceartacha.'''
ENCODING_JPN = '''日本語（にほんご、にっぽんご[注 2]）は、日本国内や、かつての日本領だった国、そして国外移民や移住者を含む日本人同士の間で使用されている言語。日本は法令によって公用語を規定していないが、法令その他の公用文は全て日本語で記述され、各種法令[注 3]において日本語を用いることが規定され、学校教育においては「国語」の教科として学習を行う等、事実上、日本国内において唯一の公用語となっている。

使用人口について正確な統計はないが、日本国内の人口、及び日本国外に住む日本人や日系人、日本がかつて統治した地域の一部住民など、約1億3千万人以上と考えられている[10]。統計によって前後する場合もあるが、この数は世界の母語話者数で上位10位以内に入る人数である[11]。

また、かつて日本に委任統治されていたパラオも一部地域で日本語を公用語と定めている。'''
ENCODING_KAZ = '''Қазақ тілі (төте: قازاق ٴتىلى‎, латын: qazaq tili) — Қазақстан Республикасының мемлекеттік тілі, сонымен қатар Ресей, Өзбекстан, Қытай, Моңғолия жəне т.б. елдерде тұратын қазақтардың ана тілі.

Қазақ тілі түркі тілдерінің қыпшақ тобына, соның ішінде қарақалпақ, ноғай, қарашай тілдерімен бірге қыпшақ-ноғай тармағына жатады. Сонымен қатар қырғыз, татар, башқұрт, қарашай-балқар, құмық, қарайым, қырымтатар тілдеріне жақын.

Қазақ тілі диалектілерге бөлінбейтіні ғылыми түрде дәлелденген. Барлық өлкелердің қазақтары бір-бірін жақсы түсінеді. Бірақ кейбір ғалымдардың пікірінше қазақ тілі 3 диалектіге бөлінеді: солтүстік-шығыс, оңтүстік және батыс (ескі үш жүздің орналасқан аумағы бойынша).'''
ENCODING_KOR = '''한국어(韓國語)는 대한민국과 조선민주주의인민공화국의 공용어이다. 한국말, 조선말, 조선어로도 불린다.

고려인의 강제 이주에 의해 러시아, 우즈베키스탄 등을 포함하여 일본, 미국, 중국, 캐나다, 오스트레일리아, 필리핀, 베트남 등 세계 여러 지역에 한민족 인구가 거주하게 되면서 전 세계 각지에서 한국어가 사용 되고 있다. 2016년 1월 초 기준으로 한국어 사용 인구는 거의 대부분이 한반도와 둥베이 등지에 거주 중이며 약 8,000만 명으로 추산된다.[1]

한국어의 계통에 관해서는 옛날부터 몽골어, 터키어, 카자흐어와 같은 알타이어족으로 분류하는 학설을 한국의 주류 학계는 받아들이고 있다.[2][10] 반면에 주변 언어와 관계가 확인되지 않는 고립어[11][6][4], 또는 제주어를 포함하는 독자적인 한국어족에 속한다고 보는 학자들도 존재한다.

그러나 고립어(language isolate)설 역시 다른 고립어들과는 궤가 다르고 한국어족도 제주어를 방언으로 포함시킬지 언어로 포함시킬지에 대한 의견이 갈라져 논거가 부족하며 한국어의 계통은 여전히 논란이 분분한 주제로, 역사언어학계에서 지속적인 연구가 이루어지고 있다.'''
ENCODING_LAV = '''Latviešu valoda ir dzimtā valoda apmēram 1,7 miljoniem cilvēku, galvenokārt Latvijā, kur tā ir vienīgā valsts valoda.[3] Lielākās latviešu valodas pratēju kopienas ārpus Latvijas ir Apvienotajā Karalistē, ASV, Īrijā, Austrālijā, Vācijā, Zviedrijā, Kanādā, Brazīlijā, Krievijas Federācijā. Latviešu valoda pieder pie indoeiropiešu valodu saimes baltu valodu grupas. Senākie rakstu paraugi latviešu valodā — jau no 15. gadsimta — ir atrodami Jāņa ģildes alus nesēju biedrības grāmatās. Tajā lielākoties bija latvieši, un no 1517. gada arī brālības vecākie bija latvieši. Pirmais teksts latviski iespiests 1507. gadā izdotajā baznīcas rokasgrāmatā „AGENDA”.[4]'''
ENCODING_MLT = '''Il-Malti huwa l-ilsien nazzjonali tar-Repubblika ta' Malta. Huwa l-ilsien uffiċjali flimkien mal-Ingliż; kif ukoll wieħed mill-ilsna uffiċjali u l-uniku wieħed ta' oriġini Għarbija (Semitiku) tal-Unjoni Ewropea. Dan l-ilsien għandu sisien u għerq semitiku, ta' djalett Għarbi li ġej mit-Tramuntana tal-Afrika, għalħekk qatt ma kellu rabta mill-qrib mal-Għarbi Klassiku. Iżda tul iż-żminijiet, minħabba proċess tal-Latinizzazzjoni ta' Malta, bdew deħlin bosta elementi lingwistiċi mill-Isqalli, djalett ta' art li wkoll għaddiet minn żmien ta' ħakma Għarbija. Wara l-Isqalli beda dieħel ukoll it-Taljan, fuq kollox fiż-żmien tad-daħla tal-Kavallieri tal-Ordni ta' San Ġwann sa meta l-Ingliż ħa post it-Taljan bħala l-ilsien uffiċjali fil-Kostituzzjoni Kolonjali tal-1934. Il-Malti huwa l-ilsien waħdieni ta' għajn semitika li jinkiteb b'ittri Latini. Studju tal-2016 juri li, fil-lingwaġġ bażiku ta’ kuljum, il-Maltin kapaċi jifhmu madwar terz ta’ dak li jingħad lilhom bl-Għarbi Tuneżin li huwa Għarbi tal-Maghrebi relatat mal-Għarbi Sqalli, filwaqt li dawk li jitkellmu bl-Għarbi Tuneżin (Tuneżin) huma kapaċi jifhmu madwar 40% ta’ dak li jingħad lilhom bil-Malti.[1]'''
ENCODING_POL = '''Język polski, polszczyzna – język lechicki z grupy zachodniosłowiańskiej (do której należą również czeski, kaszubski, słowacki i języki łużyckie), stanowiącej część rodziny indoeuropejskiej. Jest językiem urzędowym w Polsce oraz należy do oficjalnych języków Unii Europejskiej. Ocenia się, że jest mową ojczystą ok. 44 mln ludzi na świecie[1] (w literaturze naukowej można spotkać szacunki od 39[2][3] do 48 mln[4]). Językiem tym posługują się przede wszystkim mieszkańcy Polski oraz przedstawiciele tak zwanej Polonii, czyli ludności polskiej zamieszkałej za granicą.

Z punktu widzenia typologii jest językiem fleksyjnym[8], z rozbudowaną fleksją w zakresie morfologii[9]. Akcent w języku polskim pada zwykle na drugą sylabę od końca, a w zdaniu przeważa szyk SVO (podmiot orzeczenie dopełnienie)[10]. Język polski ma obecnie największą społeczność użytkowników wśród przedstawicieli słowiańszczyzny zachodniej i jest drugim językiem słowiańskim pod względem liczby użytkowników[11][12][13]. Dziś cechuje się słabo zaznaczonym i zanikającym zróżnicowaniem gwarowym, które ustępuje miejsca dominującej roli języka standardowego[14]. Jego regulacją zajmuje się Rada Języka Polskiego, pełniąca funkcję doradczą[15]. Do zapisu języka polskiego służy alfabet łaciński, wzbogacony o dodatkowe znaki diakrytyczne.

Wywodzi się z języka praindoeuropejskiego za pośrednictwem prasłowiańskiego. Spośród głównych języków słowiańskich wykazuje najbliższe pokrewieństwo ze słowackim[13] i czeskim[14], ale dzieli również wiele cech z językiem ukraińskim ze względu na długotrwałe kontakty obu języków[14][16]. Na język polski duży wpływ wywarły także języki germańskie, zwłaszcza niemiecki i jidysz oraz italskie, takie jak łacina i francuski, które rzutowały na polską leksykę i gramatykę[17][18][19]. Historycznie polszczyzna była istotną lingua franca w regionie Europy Środkowo-Wschodniej, o znaczeniu akademickim i dyplomatycznym[20][21]. Współcześnie dominuje na terenie Polski, kraju stosunkowo jednolitego pod względem językowym[10], używany jest w krajach ościennych z polską ludnością autochtoniczną stanowiącą mniejszość narodową oraz przez Polonię na całym świecie.'''
ENCODING_POR = '''A língua portuguesa, também designada português, é uma língua indo-europeia românica flexiva ocidental originada no galego-português falado no Reino da Galiza e no norte de Portugal. Com a criação do Reino de Portugal em 1139 e a expansão para o sul na sequência da Reconquista, deu-se a difusão da língua pelas terras conquistadas e mais tarde, com as descobertas portuguesas, para o Brasil, África e outras partes do mundo.[3] O português foi usado, naquela época, não somente nas cidades conquistadas pelos portugueses, mas também por muitos governantes locais nos seus contatos com outros estrangeiros poderosos. Especialmente nessa altura a língua portuguesa também influenciou várias línguas.[4]

Durante a Era dos Descobrimentos, marinheiros portugueses levaram o seu idioma para lugares distantes. A exploração foi seguida por tentativas de colonizar novas terras para o Império Português e, como resultado, o português dispersou-se pelo mundo. Brasil e Portugal são os dois únicos países cuja língua primária é o português. É língua oficial em antigas colônias portuguesas, nomeadamente, Moçambique, Angola, Cabo Verde, Guiné Equatorial,[5][6][7] Guiné-Bissau e São Tomé e Príncipe, todas na África.[8] Além disso, por razões históricas, falantes do português, ou de crioulos portugueses, são encontrados também em Macau (China), Timor-Leste, em Damão e Diu e no estado de Goa (Índia), Malaca (Malásia), em enclaves na ilha das Flores (Indonésia), Baticaloa no (Sri Lanka) e nas ilhas ABC no Caribe.[9][10]

É uma das línguas oficiais da União Europeia, do Mercosul, da União de Nações Sul-Americanas, da Organização dos Estados Americanos, da União Africana e dos Países Lusófonos. Com aproximadamente 280 milhões de falantes, o português é a 5.ª língua mais falada no mundo, a 3.ª mais falada no hemisfério ocidental e a mais falada no hemisfério sul do planeta.[11] O português também é conhecido como "a língua de Camões"[12] (em homenagem a uma das mais conhecidas figuras literárias de Portugal, Luís Vaz de Camões, autor de Os Lusíadas) e "a última flor do Lácio" (expressão usada no soneto Língua Portuguesa, do escritor brasileiro Olavo Bilac).[13][14][15][16][17] Miguel de Cervantes, o célebre autor espanhol, considerava o idioma "doce e agradável".[18] Em março de 2006, o Museu da Língua Portuguesa, um museu interativo sobre o idioma, foi fundado em São Paulo, Brasil, a cidade com o maior número de falantes do português em todo o mundo.[19]

O Dia Internacional da Língua Portuguesa é comemorado em 5 de maio.[20] A data foi instituída em 2009, no âmbito da Comunidade dos Países de Língua Portuguesa (CPLP), com o propósito de promover o sentido de comunidade e de pluralismo dos falantes do português. A comemoração propicia também a discussão de questões idiomáticas e culturais da lusofonia, promovendo a integração entre os povos desses nove países.[21]'''
ENCODING_RON = '''Limba română este o limbă indo-europeană din grupul italic și din subgrupul oriental al limbilor romanice. Printre limbile romanice, româna este a cincea după numărul de vorbitori, în urma spaniolei, portughezei, francezei și italienei. Din motive de diferențiere tipologică, româna mai este numită în lingvistica comparată limba dacoromână sau dialectul dacoromân. De asemenea, este înregistrată ca limbă de stat atât în România, cât și în Republica Moldova, unde circa 75% din populație o consideră limbă maternă (inclusiv sub denumirea de „limba moldovenească”).

Limba română este vorbită în toată lumea de 28 de milioane de persoane, dintre care circa 24 de milioane o au ca limbă maternă.[2] Din numărul total de vorbitori, peste 17 milioane[3] se află în România, unde româna (dialectul dacoromân) este limbă oficială și, conform recensământului populației din 2011, este limbă maternă pentru peste 90% din populație. Limba română este una dintre cele șase limbi oficiale ale Provinciei Autonome Voivodina (Serbia). De asemenea este limbă oficială sau administrativă în câteva comunități și organizații internaționale, precum Uniunea Latină sau Uniunea Europeană (de la 1 ianuarie 2007).'''
ENCODING_RUS = '''Ру́сский язы́к ([ˈruskʲɪi̯ jɪˈzɨk] Информация о файле слушать)[~ 3][⇨] — язык восточнославянской группы славянской ветви индоевропейской языковой семьи, национальный язык русского народа. Является одним из наиболее распространённых языков мира — восьмым среди всех языков мира по общей численности говорящих[6] и седьмым по численности владеющих им как родным (2022)[3]. Русский является также самым распространённым славянским языком[9] и самым распространённым языком в Европе — географически и по числу носителей языка как родного[7].

Русский язык — государственный язык Российской Федерации, один из двух государственных языков Белоруссии, один из официальных языков Казахстана, Киргизии и некоторых других стран, основной язык международного общения в Центральной Евразии, в Восточной Европе, в странах бывшего Советского Союза, один из шести рабочих языков ООН, ЮНЕСКО и других международных организаций[10][11][12][⇨].

Число владеющих русским языком в России составляет 137,5 млн человек (2010)[5]. Всего в мире на русском говорят 258,2 млн человек (2022)[6] [⇨].

Фонологический строй русского языка характеризуется исторически усложнившейся системой консонантизма, включающей 37 согласных фонем, и менее сложной системой вокализма, в которую входят 5 или 6[~ 4] гласных фонем. При этом как в системе гласных, так и в системе согласных отмечается большое разнообразие позиционных видоизменений. В частности, гласные в безударной позиции ослабляются и в ряде случаев не различаются. Ударение в русском языке — динамическое, разноместное и подвижное[13][14][⇨].

По морфологическому строю русский язык преимущественно флективный, синтетический. Грамматическое значение лексем передаётся, как правило, с помощью флексий. Каждая флексия обычно выражает одновременно несколько значений. Наряду с синтетическими формами, в русском языке наблюдается также развитие элементов аналитизма[13][⇨].

Синтаксис русского языка характеризуется относительно свободным порядком слов, противопоставлением однокомпонентных и двухкомпонентных структур простых предложений, наличием трёх видов сложных предложений, активной ролью интонационных средств[15][⇨].

Лексический состав русского языка в своей основе — исконно русский. Средства пополнения словарного фонда — образование слов по собственным моделям и заимствования. К ранним заимствованиям относят славянизмы, грецизмы и тюркизмы. C XVIII века преобладают голландские, немецкие и французские заимствования, с XX века — англицизмы[15][⇨].

Диалекты русского языка группируются в два наречия: северное и южное. Между наречиями локализуются переходные среднерусские говоры, ставшие основой современного литературного языка[10][⇨].

В истории русского языка выделяют три основных периода: древнерусский, общий для русского, белорусского и украинского языков (VI—XIV веков), старорусский или великорусский (XIV—XVII веков) и период национального русского языка (с середины XVII века)[16][⇨]. В основе письменности лежит старославянская кириллица[⇨].

Комплекс наук о русском языке называется лингвистической русистикой[10][15][⇨].'''
ENCODING_TGK = '''Забони тоҷикӣ (дар солҳои 1989—1991 — забони форсии тоҷикӣ; 1991—1999 – забони тоҷикии форсӣ, дарӣ: زبان تاجیکی) — забони давлатии кишварҳои Тоҷикистон, Эрон (варианти форсӣ) ва Афғонистон (дарӣ) мебошад. Ин забон ба хонаводаи забонҳои ҳинду аврупоӣ дохил мешавад. Дар маҷмӯъ: порсигӯёни асил (форсӣ, тоҷикӣ, дарӣ) зиёда аз 122 млн нафар мебошанд. Фақат ба гӯиши тоҷикӣ (бидуни дарӣ) зиёда аз 16 миллион (2022) нафар ҳарф мезананд.

Дар рушди забони тоҷикӣ дар намуди кунуниаш Садриддин Айнӣ саҳми зиёд гузоштааст.


Забони тоҷикӣ ва забони тоҷикии дарӣ (бо ранги сабз) ва дигар забонҳои эронии шарқӣ, ва туркӣ
Забони тоҷикӣ яке аз забонҳои бостонтарини ҷаҳон ба шумор меравад. Давраи нави инкишофи он дар асрҳои VII-VIII оғоз шудааст. Бо ин забон шоирону нависандагони бузург Рӯдакӣ, Фирдавсӣ, Хайём, Сино, Ҷомӣ, Мавлоно, Ҳофиз, Аҳмади Дониш, Айнӣ, Лоҳутӣ, Турсунзода, Пайрав Сулаймонӣ, Абдусалом Деҳотӣ, Убайд Раҷаб, Наимҷон Назирӣ ва дигарон асарҳои безавол эҷод кардаанд.'''
ENCODING_THA = '''ภาษาไทย หรือ ภาษาไทยกลาง เป็นภาษาในกลุ่มภาษาไท ซึ่งเป็นกลุ่มย่อยของตระกูลภาษาขร้า-ไท และเป็นภาษาราชการ และภาษาประจำชาติของประเทศไทย[3][4] มีการสันนิษฐานว่าภาษาในตระกูลนี้มีถิ่นกำเนิดจากทางตอนใต้ของประเทศจีน และนักภาษาศาสตร์บางส่วนเสนอว่า ภาษาไทยน่าจะมีความเชื่อมโยงกับตระกูลภาษาออสโตร-เอเชียติก ตระกูลภาษาออสโตรนีเซียน และตระกูลภาษาจีน-ทิเบต

ภาษาไทยเป็นภาษาที่มีระดับเสียงของคำแน่นอนหรือวรรณยุกต์เช่นเดียวกับภาษาจีน และออกเสียงแยกคำต่อคำ

ภาษาไทยปรากฏครั้งแรกในพุทธศักราช 1826 โดยพ่อขุนรามคำแหง และปรากฏอย่างสากลและใช้ในงานของราชการ เมื่อวันที่ 31 มีนาคม พุทธศักราช 2476 ด้วยการก่อตั้งสำนักงานราชบัณฑิตยสภาขึ้น และปฏิรูปภาษาไทย พุทธศักราช 2485'''
ENCODING_TUR = '''Türkçe ya da Türk dili, Güneydoğu Avrupa ve Batı Asya'da konuşulan, Türk dilleri dil ailesine ait sondan eklemeli bir dil.[12] Türk dilleri ailesinin Oğuz dilleri grubundan bir Batı Oğuz dili olan Osmanlı Türkçesinin devamını oluşturur. Dil, başta Türkiye olmak üzere Balkanlar, Ege Adaları, Kıbrıs ve Orta Doğu'yu kapsayan eski Osmanlı İmparatorluğu coğrafyasında konuşulur.[12] Ethnologue'a göre Türkçe, yaklaşık 83 milyon konuşuru ile dünyada en çok konuşulan 16. dildir.[13] Türkçe Türkiye, Kıbrıs Cumhuriyeti ve Kuzey Kıbrıs'ta ulusal resmî dil statüsüne sahiptir.[12]

Türkçe, diğer pek çok Türk dili ile de paylaştığı sondan eklemeli olması ve ünlü uyumu gibi dil bilgisi özellikleri ile karakterize edilir. Dil, tümce yapısı açısından genellikle özne-nesne-yüklem sırasına sahiptir. Almanca, Arapça gibi dillerin aksine gramatik cinsiyetin (erillik, dişilik, cinsiyet ayrımı) bulunmadığı Türkçede sözcüklerin bir kısmı Arapça, Farsça ve Fransızca gibi yabancı dillerden geçmedir. Ayrıca Azerice, Gagavuzca ve Türkmence gibi diğer Oğuz dilleri ile Türkçe yüksek oranda karşılıklı anlaşılabilirlik gösterir.[14]

Türkçe 1928'de Atatürk önderliğinde gerçekleştirilmiş Harf Devrimi'nden beri Latin alfabesini temel alan Türk alfabesi ile yazılır. Standart Türkçedeki Yazım kuralları Türk Dil Kurumu tarafından denetlenir. İstanbul Türkçesi olarak da adlandırılan İstanbul ağzı,[15] Türkçenin standart formudur ve Türkçe yazı dili bu ağzı temel alır. Bununla birlikte Güneydoğu Avrupa ve Orta Doğu'da çeşitli Türkçe şiveleri bulunur ve bu şiveler İstanbul Türkçesi ile çeşitli ses ve dilbilgisi farklılıklarına sahiptir.'''
ENCODING_UKR = '''Украї́нська мо́ва (МФА: [ukrɑ̽ˈjɪnʲsʲkɑ̽ ˈmɔwɑ̽], історичні назви — ру́ська, руси́нська[10][11][12][* 1]) — національна мова українців. Належить до східнослов'янської групи слов'янських мов, що входять до індоєвропейської мовної сім'ї, поряд з романськими, германськими, кельтськими, грецькою, албанською, вірменською та найближче спорідненими зі слов'янськими балтійськими мовами[13][14][* 2]. Є державною мовою в Україні[13][15].

Число мовців — орієнтовно 45 млн, більшість із яких мешкає в Україні. Поширена також у Білорусі[16], Молдові[17][18], Польщі[19], Росії[20][21], Румунії[22], Словаччині[23], Казахстані[24], Аргентині, Бразилії, Великій Британії[25], Канаді[26], США[27] та інших країнах, де живуть українці. Українською мовою у світі послуговуються приблизно від 40 до 45 млн осіб; вона є другою чи третьою слов'янською мовою за кількістю мовців (після російської та, можливо, польської)[13] та входить до третього десятка найпоширеніших мов світу[* 3].

Українську мову вивчає українське мовознавство, а також досліджує україністика (українознавство). Довкола походження та становлення української мови є декілька гіпотез[28] — праслов'янська[29][30][31], давньоруська[32][33], південноруська X-XI століття[34][35] та інші[* 4]. Але на сьогодні остаточно спростовані теорії про давньоруську мовну єдність[13].

Згідно з нещодавно оприлюдненою гіпотезою К. М. Тищенка, українська мова відбиває утворення українців як етносу, що сталося у VI-XVI століттях унаслідок злиття діалектів трьох слов'янських племен — полян, деревлян та сіверян за участі груп іраномовного та тюркомовного степового населення[36]. У XVIII—XX століттях українська мова зазнавала утисків із боку польської та російської влади[* 5]. Противники української мови створили численні міфи щодо української мови.

Для запису української мови використовують пристосовану кирилицю («гражданка»).

Норми української мови встановлюються у словниках української мови й українському правописі[37], які затверджуються Міністерством освіти та науки за рекомендаціями фахівців з української мови наукових установ Національної академії наук, інших наукових установ, вищих навчальних закладів[38]. До наукових установ Національної академії наук України, зокрема, належать такі: Інститут української мови НАН України (історія, граматика, лексикологія, термінологія, ономастика, стилістика та культура мови, діалектологія, соціолінгвістика), Український мовно-інформаційний фонд НАН України (комп'ютерна лінгвістика, словники), Інститут мовознавства ім. О. О. Потебні НАН України (українська мова у зв'язках з іншими мовами).

Центральний орган виконавчої влади, який забезпечує розробку та впроваджує державну мовну політику — Міністерство культури України.

Щороку 9 листопада в Україні святкують День української писемності та мови. Цього дня відбувається щорічний флешмоб — Всеукраїнський радіодиктант національної єдності — акція Українського радіо, що об'єднує українців по всьому світу навколо української мови.'''
ENCODING_URD = '''اُردُو[8] برصغیر کی معیاری زبانوں میں سے ایک ہے۔ یہ پاکستان کی قومی اور رابطہ عامہ کی زبان ہے، جبکہ بھارت کی چھ ریاستوں کی دفتری زبان کا درجہ رکھتی ہے۔ آئین ہند کے مطابق اسے 22 دفتری شناخت زبانوں میں شامل کیا جاچکا ہے۔ 2001ء کی مردم شماری کے مطابق اردو کو بطور مادری زبان بھارت میں 5.01% فیصد لوگ بولتے ہیں اور اس لحاظ سے یہ بھارت کی چھٹی بڑی زبان ہے جبکہ پاکستان میں اسے بطور مادری زبان 7.59% فیصد لوگ استعمال کرتے ہیں، یہ پاکستان کی پانچویں بڑی زبان ہے۔ اردو تاریخی طور پر ہندوستان کی مسلم آبادی سے جڑی ہے۔ [9] بعض ذخیرہ الفاظ کے علاوہ یہ زبان معیاری ہندی سے قابل فہم ہے جو اس خطے کی ہندوؤں سے منسوب ہے۔ زبانِ اردو کو پہچان و ترقی اس وقت ملی جب برطانوی دور میں انگریز حکمرانوں نے اسے فارسی کی بجائے انگریزی کے ساتھ شمالی ہندوستان کے علاقوں اور جموں و کشمیر میں اسے سنہ 1846ء اور پنجاب میں سنہ 1849ء میں بطور دفتری زبان نافذ کیا۔ اس کے علاوہ خلیجی، یورپی، ایشیائی اور امریکی علاقوں میں اردو بولنے والوں کی ایک بڑی تعداد آباد ہے جو بنیادی طور پر جنوبی ایشیاء سے کوچ کرنے والے اہلِ اردو ہیں۔ 1999ء کے اعداد و شمار کے مطابق اردو زبان کے مجموعی متکلمین کی تعداد دس کروڑ ساٹھ لاکھ کے لگ بھگ تھی۔ اس لحاظ سے یہ دنیا کی نویں بڑی زبان ہے۔

اُردو کا بعض اوقات ہندی کے ساتھ موازنہ کیا جاتا ہے۔ اُردو اور ہندی میں بُنیادی فرق یہ ہے کہ اُردو نستعلیق رسم الخط میں لکھی جاتی ہے اور عربی و فارسی الفاظ استعمال کرتی ہے۔ جبکہ ہندی زبان دیوناگری رسم الخط میں لکھی جاتی ہے اور سنسکرت الفاظ زیادہ استعمال کرتی ہے۔ کچھ ماہرینِ لسانیات اُردو اور ہندی کو ایک ہی زبان کی دو معیاری صورتیں گردانتے ہیں۔ تاہم، دیگر ماہرین اِن دونوں کو معاش اللسانی تفرّقات کی بنیاد پر الگ الگ سمجھتے ہیں۔ بلکہ حقیقت یہ ہے کہ ہندی، اُردو سے نکلی ہے۔ اسی طرح اگر اردو اور ہندی زبان کو ایک سمجھا جائے تو یہ دنیا کی چوتھی بڑی زبان ہے۔

اردو زبان دنیا کی نئی زبانوں میں سے ہونے کے باوجود اپنے پاس معیاری اور وسیع ذخیرہ ادب رکھتی ہے۔ خاص کر جنوبی ایشیائی زبانوں میں اردو اپنی شاعری کے حوالے سے جانی جاتی ہے۔'''
ENCODING_VIE = '''Tiếng Việt, cũng gọi là tiếng Việt Nam[9] hay Việt ngữ là ngôn ngữ của người Việt và là ngôn ngữ chính thức tại Việt Nam. Đây là tiếng mẹ đẻ của khoảng 85% dân cư Việt Nam cùng với hơn 4 triệu người Việt kiều. Tiếng Việt còn là ngôn ngữ thứ hai của các dân tộc thiểu số tại Việt Nam và là ngôn ngữ dân tộc thiểu số được công nhận tại Cộng hòa Séc.

Dựa trên từ vựng cơ bản, tiếng Việt được phân loại là một ngôn ngữ thuộc ngữ hệ Nam Á. Tiếng Việt là ngôn ngữ có nhiều người nói nhất trong ngữ hệ này (nhiều hơn tổng số người nói của tất cả các ngôn ngữ còn lại trong ngữ hệ). Vì Việt Nam thuộc Vùng văn hoá Đông Á, tiếng Việt cũng chịu nhiều ảnh hưởng về từ tiếng Hán, do vậy là ngôn ngữ có ít điểm tương đồng nhất với các ngôn ngữ khác trong ngữ hệ Nam Á.'''

# Texts
TEXT_CAT = ["El català (denominació oficial a Catalunya, a les Illes Balears, a Andorra, a la ciutat de l'Alguer i tradicional a Catalunya del Nord) o valencià (denominació oficial al País Valencià i tradicional al Carxe) és una llengua romànica parlada a Catalunya, el País Valencià (tret d'algunes comarques i localitats de l'interior), les Illes Balears (on també rep el nom de mallorquí, menorquí, eivissenc o formenterer segons l'illa), Andorra, la Franja de Ponent (a l'Aragó), la ciutat de l'Alguer (a l'illa de Sardenya), la Catalunya del Nord,[8] el Carxe (un petit territori de Múrcia poblat per pobladors valencians),[9][10] i en comunitats arreu del món (entre les quals destaca la de l'Argentina, amb 200.000 parlants).[11]", " ", "Té deu milions de parlants, dels quals quasi la meitat ho són de llengua materna; el seu domini lingüístic, amb una superfície de 68.730 km² i 13.529.127 d'habitants (2009),[12] inclou 1.687 termes municipals.", ' ', 'Com a llengua materna, és parlada per quatre milions de persones (29% de la població del territori lingüístic), de les quals 2.263.000 a Catalunya,[13] 1.521.000 al País Valencià[14] i 417.000 a les Illes Balears.[15]', ' ', "Com les altres llengües romàniques, el català prové del llatí vulgar que parlaven els romans que s'establiren a Hispània durant l'edat antiga."]
TEXT_ZHO_CN = ['汉语又称中文、华语[3]、唐话[4]，概指由上古汉语（先秦雅言）发展而来、书面使用汉字的分析语，为汉藏语系最大的一支语族。', '如把整个汉语族视为单一语言，则汉语为世界使用人数最多的语言，目前全世界有五分之一人口将汉语做为母语或第二语言。']
TEXT_ZHO_TW = ['漢語又稱中文、華語[3]、唐話[4]，概指由上古漢語（先秦雅言）發展而來、書面使用漢字的分析語，為漢藏語系最大的一支語族。', '如把整個漢語族視為單一語言，則漢語為世界使用人數最多的語言，目前全世界有五分之一人口將漢語做為母語或第二語言。']
TEXT_HRV = ['Hrvatski jezik (ISO 639-3: hrv) skupni je naziv za nacionalni standardni jezik Hrvata, te za skup narječja i govora kojima govore ili su nekada govorili Hrvati.', ' ', 'Njime govori više od 5,5 milijuna ljudi[2], poglavito Hrvata u Hrvatskoj (3 980 000; popis iz 2001.) i Bosni i Hercegovini (469 000; 2004.).[3]', ' ', 'Hrvatski je materinski jezik za Hrvate u drugim zemljama; Sjedinjenim Američkim Državama (58 400; popis iz 2000.);[1] Austriji, 19 400 (popis iz 2001.); Srbiji 19 223 popis 2011.', ' ', ' Inačica izvorne stranice arhivirana 4. ožujka 2022.; Mađarskoj, (14 300; popis iz 2001.); Italiji (3500; Vincent 1987.); Crnoj Gori (6810; 2006.); Slovačkoj, 890; popis iz 2001.).']
TEXT_CES = ['Čeština neboli český jazyk je západoslovanský jazyk, nejbližší slovenštině, poté lužické srbštině a polštině.', ' ', 'Patří mezi slovanské jazyky, do rodiny jazyků indoevropských.', ' ', 'Čeština se vyvinula ze západních nářečí praslovanštiny na konci 10. století.', ' ', 'Je částečně ovlivněná latinou a němčinou.', ' ', 'Česky psaná literatura se objevuje od 14. století.', ' ', 'První písemné památky jsou však již z 12. století.']
TEXT_DAN = ['Dansk er et østnordisk sprog indenfor den germanske gren af den indoeuropæiske sprogfamilie.', ' ', 'Det danske sprog tales af ca. seks millioner mennesker, hovedsageligt i Danmark, men også i Sydslesvig (i Flensborg ca. 20 %), på Færøerne og Grønland.[1]', ' ', 'Dansk er tæt beslægtet med norsk, svensk og islandsk, og sproghistorisk har dansk været stærkt påvirket af plattysk.']
TEXT_NLD = ['Het Nederlands is een West-Germaanse taal en de officiële taal van Nederland, Suriname en een van de drie officiële talen van België.', ' ', 'Binnen het Koninkrijk der Nederlanden is het Nederlands ook een officiële taal van Aruba, Curaçao en Sint-Maarten.', ' ', 'Het Nederlands is de op twee na meest gesproken Germaanse taal.']
TEXT_ENG_GB = TEXT_ENG_US = ['English is a West Germanic language in the Indo-European language family, with its earliest forms spoken by the inhabitants of early medieval England.[3][4][5]', ' ', 'It is named after the Angles, one of the ancient Germanic peoples that migrated to the island of Great Britain.', ' ', 'Existing on a dialect continuum with Scots, and then most closely related to the Low German and Frisian languages, English is genealogically Germanic.', ' ', 'However, its vocabulary also shows major influences from French (about 28% of Modern English words) and Latin (also about 28%),[6] plus some grammar and a small amount of core vocabulary influenced by Old Norse (a North Germanic language).[7][8][9]', ' ', 'Speakers of English are called Anglophones.']
TEXT_EST = ['Eesti keelel on kaks suuremat murderühma (põhjaeesti ja lõunaeesti), mõnes käsitluses eristatakse ka kirderanniku murdeid eraldi murderühmana.', ' ', 'Liikumisvõimaluste laienemine ning põhjaeesti keskmurde alusel loodud normitud eesti kirjakeele kasutus on põhjustanud murdeerinevuste taandumise.']
TEXT_FIN = ['Suomen kieli eli suomi on uralilaisten kielten itämerensuomalaiseen ryhmään kuuluva kieli, jota puhuvat pääosin suomalaiset.', ' ', 'Suomessa suomen kieltä puhuu äidinkielenään 4,8 miljoonaa ja toisena kielenään 0,5 miljoonaa ihmistä.', ' ', 'Suurimmat suomea puhuvat vähemmistöt ovat Ruotsissa, Norjassa ja Venäjällä.']
TEXT_FRA = ["Le français est parlé, en 2023, sur tous les continents par environ 321 millions de personnes5,2 : 235 millions l'emploient quotidiennement, et 90 millions3 en sont des locuteurs natifs.", ' ', "En 2018, 80 millions d'élèves et étudiants s'instruisent en français dans le monde6.", ' ', "Selon l'Organisation internationale de la francophonie (OIF), il pourrait y avoir 700 millions de francophones sur Terre en 20507."]
TEXT_DEU_AT = TEXT_DEU_DE = TEXT_DEU_CH = ['Das Deutsche ist eine plurizentrische Sprache, enthält also mehrere Standardvarietäten in verschiedenen Regionen.', ' ', 'Ihr Sprachgebiet umfasst Deutschland, Österreich, die Deutschschweiz, Liechtenstein, Luxemburg, Ostbelgien, Südtirol, das Elsass und Lothringen sowie Nordschleswig.', ' ', 'Außerdem ist Deutsch eine Minderheitensprache in einigen europäischen und außereuropäischen Ländern, z. B. in Rumänien und Südafrika sowie Nationalsprache im afrikanischen Namibia.', ' ', 'Deutsch ist die meistgesprochene Muttersprache in der Europäischen Union (EU).[27]']
TEXT_ELL = ['Η ελληνική γλώσσα ανήκει στην ινδοευρωπαϊκή οικογένεια[9] και αποτελεί το μοναδικό μέλος του ελληνικού κλάδου, ενώ είναι η επίσημη γλώσσα της Ελλάδας και της Κύπρου.', ' ', 'Ανήκει επίσης στο βαλκανικό γλωσσικό δεσμό.', ' ', 'Στην ελληνική γλώσσα, έχουμε γραπτά κείμενα ήδη από τον 15ο αιώνα π.Χ..', ' ', 'Σαν Παγκόσμια Ημέρα Ελληνικής Γλώσσας, κάθε έτος, έχει καθιερωθεί η 9η Φεβρουαρίου.', ' ', 'Έχει την μακροβιότερη καταγεγραμμένη ιστορία από οποιαδήποτε άλλη ζωντανή ινδοευρωπαϊκή γλώσσα με τουλάχιστον 3.400 χρόνια γραπτής ιστορίας.[10]', ' ', 'Γράφεται με το ελληνικό αλφάβητο το οποίο χρησιμοποιείται για περίπου 2.600 χρόνια.[11][12]', ' ', 'Προηγουμένως η ελληνική γλώσσα γραφόταν με τη Γραμμική Β και το κυπριακό συλλαβάριο.[13]', ' ', 'Το ελληνικό αλφάβητο προέρχεται από το φοινικικό αλφάβητο.', ' ', 'Στο ελληνικό αλφάβητο βασίζεται το λατινικό, το κυριλλικό, το αρμενικό, το κοπτικό, το γοτθικό και πολλά άλλα αλφάβητα.']
TEXT_ITA = ['È classificato al 23º posto tra le lingue per numero di parlanti nel mondo e, in Italia, è utilizzato da circa 58 milioni di residenti.[2]', ' ', "Nel 2015 l'italiano era la lingua materna del 90,4% dei residenti in Italia,[3] che spesso lo acquisiscono e lo usano insieme alle varianti regionali dell'italiano, alle lingue regionali e ai dialetti.", ' ', "In Italia viene ampiamente usato per tutti i tipi di comunicazione della vita quotidiana ed è largamente prevalente nei mezzi di comunicazione nazionali, nell'amministrazione pubblica dello Stato italiano e nell'editoria."]
TEXT_JPN = ['日本語（にほんご、にっぽんご[注 2]）は、日本国内や、かつての日本領だった国、そして国外移民や移住者を含む日本人同士の間で使用されている言語。', '日本は法令によって公用語を規定していないが、法令その他の公用文は全て日本語で記述され、各種法令[注 3]において日本語を用いることが規定され、学校教育においては「国語」の教科として学習を行う等、事実上、日本国内において唯一の公用語となっている。']
TEXT_KHM = ['ភាសាខ្មែរ គឺជាភាសាកំណើតរបស់ជនជាតិខ្មែរនិងជាភាសាផ្លូវការរបស់ប្រទេសកម្ពុជា។', ' ', 'ភាសាសំស្ក្រឹតនិងភាសាបាលីបាន\u200Bជួយបង្កើតខេមរភាសា ព្រោះភាសាខ្មែរបានខ្ចីពាក្យច្រើនពីភាសាទាំងពីរនេះ។', ' ', '\u200Bមានអក្សរក្រមវែងជាងគេនៅលើពិភពលោក ។\u200B', ' ', 'វាជាភាសាមួយដ៏ចំណាស់\u200B ដែលប្រហែលជាមានដើមកំណើតតាំងតែពី\u200B២០០០ឆ្នាំមុនមកម៉្លេះ។']
TEXT_KOR = ['한국어(韓國語)는 대한민국과 조선민주주의인민공화국의 공용어이다.', ' ', '한국말, 조선말, 조선어로도 불린다.']
TEXT_LIT = ['Lietuvių kalba – iš baltų prokalbės kilusi lietuvių tautos kalba, kuri Lietuvoje yra valstybinė, o Europos Sąjungoje – viena iš oficialiųjų kalbų.', ' ', 'Lietuviškai kalba apie tris milijonus žmonių (dauguma jų gyvena Lietuvoje).', ' ', 'Drauge su latvių, mirusiomis prūsų, jotvingių ir kitomis baltų kalbomis priklauso indoeuropiečių kalbų šeimos baltų kalbų grupei.']
TEXT_MKD = ['Македонски јазик — јужнословенски јазик, дел од групата на словенски јазици од јазичното семејство на индоевропски јазици.', ' ', 'Македонскиот е службен и национален јазик во Македонија, а воедно е и официјално признат како регионален службен јазик во Горица и Пустец во Албанија каде што живее бројно македонско население, но и во Србија како официјален во општините Јабука и Пландиште, Романија и Косово.', ' ', 'Македонски се зборува и во Австралија, Бугарија, Грција, Канада, САД, Црна Гора, Турција, во некои земји−членки на Европската Унија и останатата македонска дијаспора.', ' ', 'Вкупниот број на македонски говорници е тешко да се утврди поради несоодветни пописи, но бројката се движи од околу 2,5 до 3 милиони луѓе.']
TEXT_MAL = ['ഇന്ത്യയിൽ കേരള സംസ്ഥാനത്തിലും കേന്ദ്രഭരണപ്രദേശങ്ങളായ ലക്ഷദ്വീപിലും പോണ്ടിച്ചേരിയുടെ ഭാഗമായ മാഹിയിലും തമിഴ്നാട്ടിലെ കന്യാകുമാരി ജില്ലയിലും നീലഗിരി ജില്ലയിലെ ഗൂഡല്ലൂർ താലൂക്കിലും സംസാരിക്കപ്പെടുന്ന ഭാഷയാണ് മലയാളം.', ' ', 'ഇതു ദ്രാവിഡ ഭാഷാ കുടുംബത്തിൽപ്പെടുന്നു.', ' ', 'ഇന്ത്യയിൽ ശ്രേഷ്ഠഭാഷാ പദവി ലഭിക്കുന്ന അഞ്ചാമത്തെ ഭാഷയാണ് മലയാളം[5].', ' ', '2013 മെയ് 23-നു ചേർന്ന കേന്ദ്രമന്ത്രിസഭായോഗമാണ് മലയാളത്തെ ശ്രേഷ്ഠഭാഷയായി അംഗീകരിച്ചത്.', ' ', 'ക്ലാസിക്കൽ ലാംഗ്വേജ് എന്ന പദവിയാണ് ലൽകിയത്.', ' ', 'അതിനു മലയാളത്തിൽ നൽകിയ വിവർത്തനം ആണ് ശ്രേഷ്ഠഭാഷ എന്നത്.', ' ', 'വാസ്തവത്തിൽ ഇത് അത്രശരിയായ വിവർത്തനമോ ശരിയായ പ്രയോഗമോ അല്ല.', ' ', 'ശ്രേഷ്ഠം മോശം എന്ന നിലയിൽ ഭാഷകളെ വിലയിരുത്തുന്നത് ശാസ്ത്രീയമായ കാര്യമല്ല.', ' ', 'ഭാഷകളിൽ ശ്രേഷ്ഠമെന്നും അല്ലാത്തത് എന്നുമുള്ള വിഭജനം ഇല്ല.', ' ', 'ഇന്ത്യൻ ഭരണഘടനയിലെ എട്ടാം ഷെഡ്യൂളിൽ ഉൾപ്പെടുത്തിയിരിക്കുന്ന ഇന്ത്യയിലെ ഇരുപത്തിരണ്ട് ഔദ്യോഗിക ഭാഷകളിൽ ഒന്നാണ് മലയാളം[6].', ' ', 'മലയാള ഭാഷ കൈരളി,മലനാട് ഭാഷ എന്നും അറിയപ്പെടുന്നു.', 'കേരള സംസ്ഥാനത്തിലെ ഭരണഭാഷയും കൂടിയാണ്‌ മലയാളം.', ' ', 'കേരളത്തിനും ലക്ഷദ്വീപിനും പുറമേ തമിഴ്നാട്ടിലെ ചില ഭാഗങ്ങളിലും കന്യാകുമാരി ജില്ല, നീലഗിരി ജില്ല കർണാടകയുടെ ദക്ഷിണ കന്നഡ ജില്ല, കൊടഗ് ഭാഗങ്ങളിലും ഗൾഫ് രാജ്യങ്ങൾ, സിംഗപ്പൂർ, മലേഷ്യ എന്നിവിടങ്ങളിലെ കേരളീയ പൈതൃകമുള്ള അനേകം ജനങ്ങളും മലയാളം ഉപയോഗിച്ചുപോരുന്നു.', 'ദേശീയ ഭാഷയായി ഉൾപ്പെടുത്തിയത് മറ്റ് 21 ഭാഷകളുടേതുപോലെ തനതായ വ്യക്തിത്വം ഉള്ളതിനാലാണ്.', ' ', 'മലയാള ഭാഷയുടെ ഉല്പത്തിയും പ്രാചീനതയും സംബന്ധിച്ച കാര്യങ്ങൾ ഇന്നും അവ്യക്തമാണ്.', ' ', 'പഴയ തമിഴിനും മുൻപത്തെ മൂലദ്രാവിഡമാണ് മലയാളത്തിന്റെ ആദ്യ രൂപം എന്നു കരുതുന്നു.', 'യു.എ.ഇ-യിലെ നാല് ഔദ്യോഗിക ഭാഷകളിൽ ഒന്നു മലയാളമാണ്.[അവലംബം ആവശ്യമാണ്]']
TEXT_NOB = ['Bokmål er en varietet av norsk skriftspråk.', ' ', 'Bokmål er en av to offisielle målformer av norsk skriftspråk, hvorav den andre er nynorsk.', ' ', 'I skrift har 87,3% bokmål som hovedmål i skolen.[1]', ' ', 'Etter skriftreformene av riksmål i 1987 og bokmål i 1981 og 2005 er det lite som skiller bokmål og riksmål i alminnelig bruk.']
TEXT_NNO = ['Nynorsk, før 1929 offisielt kalla landsmål, er sidan jamstillingsvedtaket av 12. mai 1885 ei av dei to offisielle målformene av norsk; den andre forma er bokmål.', ' ', 'Nynorsk vert i dag nytta av om lag 10–15% av innbyggjarane i Noreg.[1][2]', ' ', 'Skriftspråket er basert på nynorsk talemål, det vil seie dei moderne norske dialektane til skilnad frå gamalnorsk og mellomnorsk.', ' ', 'Når ein seier at nokon snakkar nynorsk, meiner ein helst at dei snakkar nynorsk normaltalemål.', ' ', 'Dei færraste dialekttalande nordmenn seier at dei snakkar nynorsk, men det er ikkje uvanleg i kjerneområda til nynorsken.', ' ', 'Dette tilhøvet mellom tale og skrift ligg bak målrørsla sitt slagord sidan 1970-talet: «Snakk dialekt – skriv nynorsk!»', ' ', 'Nynorske dialektar vart snakka over heile landet, men det er berre på Vestlandet utanom dei største byene og i dei austlandske fjellbygdene at skriftspråket står sterkt.', ' ', 'Det vil seie at dei fleste dialekttalarane har bokmål som det primære skriftspråket sitt.']
TEXT_POL = ['Język polski, polszczyzna – język lechicki z grupy zachodniosłowiańskiej (do której należą również czeski, kaszubski, słowacki i języki łużyckie), stanowiącej część rodziny indoeuropejskiej.', ' ', 'Jest językiem urzędowym w Polsce oraz należy do oficjalnych języków Unii Europejskiej.', ' ', 'Ocenia się, że jest mową ojczystą ok. 44 mln ludzi na świecie[1] (w literaturze naukowej można spotkać szacunki od 39[2][3] do 48 mln[4]).', ' ', 'Językiem tym posługują się przede wszystkim mieszkańcy Polski oraz przedstawiciele tak zwanej Polonii, czyli ludności polskiej zamieszkałej za granicą.']
TEXT_POR_BR = TEXT_POR_PT = ['A língua portuguesa, também designada português, é uma língua indo-europeia românica flexiva ocidental originada no galego-português falado no Reino da Galiza e no norte de Portugal.', ' ', 'Com a criação do Reino de Portugal em 1139 e a expansão para o sul na sequência da Reconquista, deu-se a difusão da língua pelas terras conquistadas e mais tarde, com as descobertas portuguesas, para o Brasil, África e outras partes do mundo.[6]', ' ', 'O português foi usado, naquela época, não somente nas cidades conquistadas pelos portugueses, mas também por muitos governantes locais nos seus contatos com outros estrangeiros poderosos.', ' ', 'Especialmente nessa altura a língua portuguesa também influenciou várias línguas.[7]']
TEXT_RON = ['Limba română este o limbă indo-europeană din grupul italic și din subgrupul oriental al limbilor romanice.', ' ', 'Printre limbile romanice, româna este a cincea după numărul de vorbitori, în urma spaniolei, portughezei, francezei și italienei.', ' ', 'Din motive de diferențiere tipologică, româna mai este numită în lingvistica comparată limba dacoromână sau dialectul dacoromân.', ' ', 'De asemenea, este înregistrată ca limbă de stat atât în România, cât și în Republica Moldova, unde circa 75% din populație o consideră limbă maternă (inclusiv sub denumirea de „limba moldovenească”).']
TEXT_RUS = ['Ру́сский язы́к ([ˈruskʲɪi̯ jɪˈzɨk] Информация о файле слушать)[~ 3][⇨] — язык восточнославянской группы славянской ветви индоевропейской языковой семьи, национальный язык русского народа.', ' ', 'Является одним из наиболее распространённых языков мира — восьмым среди всех языков мира по общей численности говорящих[6] и седьмым по численности владеющих им как родным (2022)[3].', ' ', 'Русский является также самым распространённым славянским языком[9] и самым распространённым языком в Европе — географически и по числу носителей языка как родного[7].']
TEXT_SLV = ['Slovenščina [sloˈʋenʃtʃina] je združeni naziv za uradni knjižni jezik Slovencev in skupno ime za narečja in govore, ki jih govorijo ali so jih nekoč govorili Slovenci.', ' ', 'Govori ga okoli 2,5 (dva in pol) milijona govorcev po svetu, od katerih jih večina živi v Sloveniji.', ' ', 'Glede na število govorcev ima razmeroma veliko narečij.', ' ', 'Slovenščina je zahodni južnoslovanski jezik in eden redkih indoevropskih jezikov, ki je ohranil dvojino.', ' ', 'Za zapisovanje slovenskega jezika se danes uporablja gajica, pisava imenovana po Ljudevitu Gaju, ki jo je priredil po češkem črkopisu.', ' ', 'Slovenska gajica se imenuje slovenica.', ' ', 'Pišemo jo od marčne revolucije 1848.', ' ', 'Do takrat smo uporabljali bohoričico.']
TEXT_SPA = ['El español o castellano es una lengua romance procedente del latín hablado, perteneciente a la familia de lenguas indoeuropeas.', ' ', 'Forma parte del grupo ibérico y es originaria de Castilla, reino medieval de la península ibérica.', ' ', 'Se conoce también informalmente como «castilla»,n. 1\u200B31\u200B32\u200B en algunas áreas rurales e indígenas de América,33\u200B pues el español se empezó a enseñar poco después de la incorporación de los nuevos territorios a la Corona de Castilla.34\u200B35\u200B36\u200B37\u200B38\u200B39\u200B']
TEXT_SWE = ['Svenska (svenska (info)) är ett östnordiskt språk som talas av ungefär tio miljoner personer främst i Sverige där språket har en dominant ställning som huvudspråk, men även som det ena nationalspråket i Finland och som enda officiella språk på Åland.', ' ', 'I övriga Finland talas det som modersmål framförallt i de finlandssvenska kustområdena i Österbotten, Åboland och Nyland.', ' ', 'En liten minoritet svenskspråkiga finns även i Estland.', ' ', 'Svenska är nära besläktat och i hög grad ömsesidigt begripligt med danska och norska.', ' ', 'De andra nordiska språken, isländska och färöiska, är mindre ömsesidigt begripliga med svenska.', ' ', 'Liksom de övriga nordiska språken härstammar svenskan från en gren av fornnordiska, vilket var det språk som talades av de germanska folken i Skandinavien.']
TEXT_THA = ['ภาษาไทย หรือ ภาษาไทยกลาง เป็นภาษาในกลุ่มภาษาไท ซึ่งเป็นกลุ่มย่อยของตระกูลภาษาขร้า-ไท และเป็นภาษาราชการ และภาษาประจำชาติของประเทศไทย[3][4]', ' ', 'มีการสันนิษฐานว่าภาษาในตระกูลนี้มีถิ่นกำเนิดจากทางตอนใต้ของประเทศจีน และนักภาษาศาสตร์บางส่วนเสนอว่า ภาษาไทยน่าจะมีความเชื่อมโยงกับตระกูลภาษาออสโตร-เอเชียติก ตระกูลภาษาออสโตรนีเซียน และตระกูลภาษาจีน-ทิเบต']
TEXT_BOD = ['བོད་ཀྱི་སྐད་ཡིག་ནི་བོད་ཡུལ་དང་ཉེ་འཁོར་གྱི་ས་ཁུལ་བལ་ཡུལ། འབྲུག་དང་འབྲས་ལྗོངས།', ' ', 'ལ་དྭགས་ནས་ལྷོ་མོན་རོང་སོགས་སུ་བེད་སྤྱོད་བྱེད་པའི་སྐད་ཡིག་དེ། ད་ཆར་ཡོངས་གྲགས་སུ་བོད་ཀྱི་ཡུལ་གྲུ་སྟོད་སྨད་བར་གསུམ་ལ་ལྟོས་ཏེ་ནང་གསེས་རིགས་གསུམ་དུ་ཕྱེ་བ་སྟེ།', ' ', 'སྟོད་དབུས་གཙང་གི་སྐད་དང་། བར་ཁམས་པའི་སྐད་དང་། སྨད་ཨ་མདོའི་སྐད་རྣམས་སོ།', ' ', 'བོད་སྐད་ནི་ཧོར་སོག་ལ་སོགས་པ་གྲངས་ཉུང་མི་རིགས་གཞན་པ་ཁག་ཅིག་གིས་བེད་སྤྱོད་གཏོང་བཞིན་ཡོད་པར་མ་ཟད། བལ་ཡུལ་དང་། འབྲས་ལྗོངས། འབྲུག་ཡུལ་།', ' ', 'རྒྱ་གར་ཤར་དང་བྱང་རྒྱུད་མངའ་སྡེ་ཁག་གཅིག་བཅས་ཀྱི་རྒྱལ་ཁབ་རྣམས་སུའང་བེད་སྤྱོད་གཏོང་བཞིན་ཡོད།']
TEXT_TUR = ["Türkçe ya da Türk dili, Güneydoğu Avrupa ve Batı Asya'da konuşulan, Türk dilleri dil ailesine ait sondan eklemeli bir dil.[12]", ' ', 'Türk dilleri ailesinin Oğuz dilleri grubundan bir Batı Oğuz dili olan Osmanlı Türkçesinin devamını oluşturur.', ' ', "Dil, başta Türkiye olmak üzere Balkanlar, Ege Adaları, Kıbrıs ve Orta Doğu'yu kapsayan eski Osmanlı İmparatorluğu coğrafyasında konuşulur.[12]", ' ', "Ethnologue'a göre Türkçe, yaklaşık 83 milyon konuşuru ile dünyada en çok konuşulan 16. dildir.[13]", ' ', "Türkçe Türkiye, Kıbrıs Cumhuriyeti ve Kuzey Kıbrıs'ta ulusal resmî dil statüsüne sahiptir.[12]"]
TEXT_UKR = ['Украї́нська мо́ва (МФА: [ukrɑ̽ˈjɪnʲsʲkɑ̽ ˈmɔwɑ̽], історичні назви — ру́ська, руси́нська[10][11][12][* 1]) — національна мова українців.', ' ', "Належить до східнослов'янської групи слов'янських мов, що входять до індоєвропейської мовної сім'ї, поряд з романськими, германськими, кельтськими, грецькою, албанською, вірменською та найближче спорідненими зі слов'янськими балтійськими мовами[13][14][* 2].", ' ', 'Є державною мовою в Україні[13][15].']
TEXT_VIE = ['Tiếng Việt, cũng gọi là tiếng Việt Nam[9] hay Việt ngữ là ngôn ngữ của người Việt và là ngôn ngữ chính thức tại Việt Nam.', ' ', 'Đây là tiếng mẹ đẻ của khoảng 85% dân cư Việt Nam cùng với hơn 4 triệu người Việt kiều.', ' ', 'Tiếng Việt còn là ngôn ngữ thứ hai của các dân tộc thiểu số tại Việt Nam và là ngôn ngữ dân tộc thiểu số được công nhận tại Cộng hòa Séc.']
TEXT_OTHER = TEXT_ENG_US

# Sentences
SENTENCE_AFR = "Afrikaans is tipologies beskou 'n Indo-Europese, Wes-Germaanse, Nederfrankiese taal,[2] wat aan die suidpunt van Afrika onder invloed van verskeie ander tale en taalgroepe ontstaan het."
SENTENCE_SQI = 'Gjuha shqipe (ose thjesht shqipja) është gjuhë dhe degë e veçantë e familjes indo-evropiane që flitet nga rreth 7-10 milionë njerëz në botë,[1] kryesisht në Shqipëri, Kosovë dhe Maqedoninë e Veriut, por edhe në zona të tjera të Evropës Juglindore ku ka një popullsi shqiptare, duke përfshirë Malin e Zi dhe Luginën e Preshevës.'
SENTENCE_AMH = 'አማርኛ[1] ፡ የኢትዮጵያ ፡ መደበኛ ፡ ቋንቋ ፡ ነው ።'
SENTENCE_ARA = 'اللُّغَة العَرَبِيّة هي أكثر اللغات السامية تحدثًا، وإحدى أكثر اللغات انتشاراً في العالم، يتحدثها أكثر من 467 مليون نسمة،(1) ويتوزع متحدثوها في الوطن العربي، بالإضافة إلى العديد من المناطق الأخرى المجاورة كالأحواز وتركيا وتشاد ومالي والسنغال وإرتيريا وإثيوبيا وجنوب السودان وإيران.'
SENTENCE_HYE = 'Հայերեն (ավանդական՝ հայերէն), հնդեվրոպական լեզվաընտանիքի առանձին ճյուղ հանդիսացող լեզու։'
SENTENCE_ASM = 'অসমীয়া ভাষা হৈছে সকলোতকৈ পূৰ্বীয় ভাৰতীয়-আৰ্য ভাষা।'
SENTENCE_AST = "L'asturianu ye una llingua romance propia d'Asturies,[1] perteneciente al subgrupu asturllionés."
SENTENCE_AZE = 'Azərbaycan dili[2][3] (Cənubi Azərbaycanda: Türk dili[4][5]) — Azərbaycan Respublikasının və Rusiya Federasiyası Dağıstan Respublikasının[6] rəsmi dövlət dili.'
SENTENCE_EUS = 'Euskara Euskal Herriko hizkuntza da.[5]'
SENTENCE_BEL = "Белару́ская мо́ва — нацыянальная мова беларусаў, уваходзіць у індаеўрапейскую моўную сям'ю, славянскую групу, усходнеславянскую падгрупу."
SENTENCE_BEN = 'বাংলা ভাষা (বাঙলা, বাঙ্গলা, তথা বাঙ্গালা নামেও পরিচিত) একটি ইন্দো-আর্য ভাষা, যা দক্ষিণ এশিয়ার বাঙালি জাতির প্রধান কথ্য ও লেখ্য ভাষা।'
SENTENCE_BUL = 'Бъ̀лгарският езѝк е индоевропейски език от групата на южнославянските езици.'
SENTENCE_CAT = TEXT_CAT[0]
SENTENCE_ZHO_CN = TEXT_ZHO_CN[0]
SENTENCE_ZHO_TW = TEXT_ZHO_TW[0]
SENTENCE_HRV = TEXT_HRV[0]
SENTENCE_CES = TEXT_CES[0]
SENTENCE_DAN = TEXT_DAN[0]
SENTENCE_NLD = TEXT_NLD[0]
SENTENCE_ENM = 'Forrþrihht anan se time comm þatt ure Drihhtin wollde ben borenn i þiss middellærd forr all mannkinne nede he chæs himm sone kinnessmenn all swillke summ he wollde and whær he wollde borenn ben he chæs all att hiss wille.'
SENTENCE_ENG_GB = SENTENCE_ENG_US = TEXT_ENG_US[0]
SENTENCE_EPO = 'Esperanto, origine la Lingvo Internacia,[4] estas la plej disvastiĝinta internacia planlingvo.[5]'
SENTENCE_EST = TEXT_EST[0]
SENTENCE_FIN = TEXT_FIN[0]
SENTENCE_FRA = TEXT_FRA[0]
SENTENCE_GLG = 'O galego ([ɡaˈleɣo̝]) é unha lingua indoeuropea que pertence á póla de linguas románicas.'
SENTENCE_LUG = 'Luganda/Oluganda lwe lulimi olwogerwa Abaganda e Yuganda.'
SENTENCE_KAT = 'ქართული ენა — იბერიულ-კავკასიურ ენათა ოჯახის ქართველურ ენათა ჯგუფის ენა.'
SENTENCE_DEU_AT = SENTENCE_DEU_DE = SENTENCE_DEU_CH = TEXT_DEU_AT[0]
SENTENCE_GRC = "Ὅτι μὲν ὑμεῖς, ὦ ἄνδρες Ἀθηναῖοι, πεπόνθατε ὑπὸ τῶν ἐμῶν κατηγόρων, οὐκ οἶδα· ἐγὼ δ' οὖν καὶ αὐτὸς ὑπ' αὐτῶν ὀλίγου ἐμαυτοῦ ἐπελαθόμην, οὕτω πιθανῶς ἔλεγον."
SENTENCE_ELL = TEXT_ELL[0]
SENTENCE_GUJ = 'ગુજરાતી ‍(/ɡʊdʒəˈrɑːti/[૭], રોમન લિપિમાં: Gujarātī, ઉચ્ચાર: [ɡudʒəˈɾɑːtiː]) ભારત દેશના ગુજરાત રાજ્યની ઇન્ડો-આર્યન ભાષા છે, અને મુખ્યત્વે ગુજરાતી લોકો દ્વારા બોલાય છે.'
SENTENCE_HEB = 'עִבְרִית (נקראת גם בשם: עברית מודרנית) היא שפה שמית, ממשפחת השפות האפרו-אסיאתיות, הידועה כשפתם של היהודים ושל השומרונים.'
SENTENCE_HIN = 'हिन्दी या हिंदी जिसके मानकीकृत रूप को मानक हिंदी कहा जाता है, विश्व की एक प्रमुख भाषा है एवं भारत की एक राजभाषा है।'
SENTENCE_HUN = 'A magyar nyelv az uráli nyelvcsalád tagja, a finnugor nyelvek közé tartozó ugor nyelvek egyike.'
SENTENCE_ISL = 'Íslenska er vesturnorrænt, germanskt og indóevrópskt tungumál sem er einkum talað og ritað á Íslandi og er móðurmál langflestra Íslendinga.[4]'
SENTENCE_IND = 'Bahasa Indonesia adalah bahasa nasional dan resmi di seluruh Indonesia.'
SENTENCE_GLE = 'Is ceann de na teangacha Ceilteacha í an Ghaeilge (nó Gaeilge na hÉireann mar a thugtar uirthi corruair), agus ceann den dtrí cinn de theangacha Ceilteacha ar a dtugtar na teangacha Gaelacha (Gaeilge, Gaeilge Mhanann agus Gaeilge na hAlban) go háirithe.'
SENTENCE_ITA = TEXT_ITA[0]
SENTENCE_JPN = TEXT_JPN[0]
SENTENCE_KAN = 'ದ್ರಾವಿಡ ಭಾಷೆಗಳಲ್ಲಿ ಪ್ರಾಮುಖ್ಯವುಳ್ಳ ಭಾಷೆಯೂ ಭಾರತದ ಪುರಾತನವಾದ ಭಾಷೆಗಳಲ್ಲಿ ಒಂದೂ ಆಗಿರುವ ಕನ್ನಡ ಭಾಷೆಯನ್ನು ಅದರ ವಿವಿಧ ರೂಪಗಳಲ್ಲಿ ಸುಮಾರು ೪೫ ದಶಲಕ್ಷ ಜನರು ಆಡು ನುಡಿಯಾಗಿ ಬಳಸುತ್ತಲಿದ್ದಾರೆ.'
SENTENCE_KHM = TEXT_KHM[0]
SENTENCE_KOR = TEXT_KOR[0]
SENTENCE_KIR = 'Кыргыз тили — Кыргыз Республикасынын мамлекеттик тили, түрк тилдеринин курамына, анын ичинде кыргыз-кыпчак же тоо-алтай тобуна кирет.'
SENTENCE_LAT = 'Lingua Latina,[1] sive sermo Latinus,[2] est lingua Indoeuropaea qua primum Latini universi et Romani antiqui in primis loquebantur quamobrem interdum etiam lingua Latia[3] (in Latio enim sueta) et lingua Romana[4] (nam imperii Romani sermo sollemnis) appellatur.'
SENTENCE_LAV = 'Latviešu valoda ir dzimtā valoda apmēram 1,7 miljoniem cilvēku, galvenokārt Latvijā, kur tā ir vienīgā valsts valoda.[3]'
SENTENCE_LIJ = "O Lìgure (in monegasco: lenga ligüra e lenga lìgura) o l'é 'na lengoa[1] do gruppo lengoìstego itàlico oçidentâ parlâ in Italia (Liguria, Piemonte, Emilia-Romagna e Sardegna), into sud da Fransa, in Còrsega, e into Prinçipato de Monego."
SENTENCE_LIT = TEXT_LIT[0]
SENTENCE_LTZ = "D'Lëtzebuergesch gëtt an der däitscher Dialektologie als ee westgermaneschen, mëtteldäitschen Dialekt aklasséiert, deen zum Muselfränkesche gehéiert."
SENTENCE_MKD = TEXT_MKD[0]
SENTENCE_MSA = 'Bahasa Melayu (Tulisan Jawi: بهاس ملايو; Rencong: ꤷꥁꤼ ꤸꥍꤾꤿꥈ) ialah salah satu daripada bahasa-bahasa Melayu-Polinesia di bawah keluarga bahasa Austronesia, yang merupakan bahasa rasmi di Brunei, Indonesia, Malaysia dan Singapura, serta dituturkan di Timor Leste dan sebahagian wilayah di Kemboja , Filipina dan Thailand.'
SENTENCE_MAL = TEXT_MAL[0]
SENTENCE_GLV = 'She Gaelg (graït: /gɪlg/) çhengey Ghaelagh Vannin.'
SENTENCE_MAR = 'मराठी भाषा ही इंडो-युरोपीय भाषाकुळातील एक भाषा आहे.'
SENTENCE_MNI = 'ꯃꯤꯇꯩꯂꯣꯟ ꯍꯥꯏꯕꯁꯤ ꯏꯟꯗꯤꯌꯥ ꯑꯋꯥꯡ-ꯅꯣꯡꯄꯣꯛꯇ ꯂꯩꯕ ꯃꯅꯤꯄꯨꯔꯗ ꯃꯔꯨꯑꯣꯏꯅ ꯉꯥꯡꯅꯕ ꯇꯤꯕꯦꯇꯣ-ꯕꯔꯃꯟ ꯀꯥꯡꯂꯨꯞꯇ ꯆꯤꯡꯕ ꯂꯣꯟ ꯑꯃꯅꯤ ꯫ ꯚꯥꯔꯠ ꯂꯩꯉꯥꯛꯅꯥ ꯁꯛꯈꯪꯂꯕ ꯂꯣꯟ ꯲꯲ ꯁꯤꯡꯒꯤ ꯃꯅꯨꯡꯗ ꯃꯤꯇꯩꯂꯣꯟꯁꯤꯁꯨ ꯑꯃꯅꯤ ꯫ ꯃꯤꯇꯩꯂꯣꯟ ꯑꯁꯤ ꯏꯟꯗꯤꯌꯥꯒꯤ ꯁ꯭ꯇꯦꯠ ꯑꯣꯏꯔꯤꯕ ꯑꯁꯥꯝ ꯑꯃꯁꯨꯡ ꯇ꯭ꯔꯤꯄꯨꯔꯥ ꯑꯃꯗꯤ ꯑꯇꯩ ꯂꯩꯕꯥꯛꯁꯤꯡꯗ ꯍꯥꯏꯕꯗꯤ ꯕꯥꯡꯂꯥꯗꯦꯁ ꯑꯃꯁꯨꯡ ꯑꯋꯥꯗꯁꯨ ꯉꯥꯡꯅꯩ ꯫ ꯏꯪ ꯀꯨꯝꯖ ꯲꯰꯱꯱ ꯒꯤ ꯃꯤꯀꯣꯛ ꯊꯤꯕꯗ ꯃꯤꯇꯩꯂꯣꯟꯕꯨ ꯏꯃꯥꯂꯣꯟ ꯑꯣꯢꯅ ꯉꯥꯡꯕꯒꯤ ꯃꯤꯁꯤꯡ ꯂꯤꯆꯥ ꯱꯸ ꯃꯨꯛ ꯁꯨꯢ ꯫'
SENTENCE_MON = 'Монгол хэл нь Монгол улсын албан ёсны хэл юм.'
SENTENCE_NEP = 'नेपाली भाषा (अन्तर्राष्ट्रिय ध्वन्यात्मक वर्णमाला [neˈpali bʱaʂa]) नेपालको सम्पर्क भाषा तथा भारत, भुटान र म्यानमारको केही भागमा मातृभाषाको रूपमा बोलिने भाषा हो।'
SENTENCE_NOB = TEXT_NOB[0]
SENTENCE_NNO = TEXT_NNO[0]
SENTENCE_ORI = 'ଓଡ଼ିଆ (ଇଂରାଜୀ ଭାଷାରେ Odia /əˈdiːə/ or Oriya /ɒˈriːə/,) ଏକ ଭାରତୀୟ ଭାଷା ଯାହା ଏକ ଇଣ୍ଡୋ-ଇଉରୋପୀୟ ଭାଷାଗୋଷ୍ଠୀ ଅନ୍ତର୍ଗତ ଇଣ୍ଡୋ-ଆର୍ଯ୍ୟ ଭାଷା ।'
SENTENCE_FAS = 'فارسی یا پارسی یک زبان ایرانی غربی از زیرگروه ایرانی شاخهٔ هندوایرانیِ خانوادهٔ زبان‌های هندواروپایی است که در کشورهای ایران، افغانستان، تاجیکستان، ازبکستان، پاکستان، عراق، ترکمنستان و آذربایجان به آن سخن می‌گویند.'
SENTENCE_POL = TEXT_POL[0]
SENTENCE_POR_BR = SENTENCE_POR_PT = TEXT_POR_BR[0]
SENTENCE_RON = TEXT_RON[0]
SENTENCE_PAN_GURU = 'ਪੰਜਾਬੀ ਭਾਸ਼ਾ /pʌnˈdʒɑːbi/ (ਸ਼ਾਹਮੁਖੀ: ‎پنجابی‎) (ਗੁਰਮੁਖੀ: ਪੰਜਾਬੀ) ਪੰਜਾਬ ਦੀ ਭਾਸ਼ਾ, ਜਿਸ ਨੂੰ ਪੰਜਾਬ ਖੇਤਰ ਦੇ ਵਸਨੀਕ ਜਾਂ ਸੰਬੰਧਿਤ ਲੋਕ ਬੋਲਦੇ ਹਨ।[1]'
SENTENCE_RUS = TEXT_RUS[0]
SENTENCE_SME = 'Davvisámegiella gullá sámegielaid oarjesámegielaid davvejovkui ovttas julev- ja bihtánsámegielain.'
SENTENCE_SAN = 'संस्कृतम् जगतः एकतमा अतिप्राचीना समृद्धा शास्त्रीया च भाषासु वर्तते।'
SENTENCE_GLA = "'S i cànan dùthchasach na h-Alba a th' anns a' Ghàidhlig."
SENTENCE_SRP_CYRL = 'Српски језик припада словенској групи језика породице индоевропских језика.[12]'
SENTENCE_SRP_LATN = 'Srpski jezik pripada slovenskoj grupi jezika porodice indoevropskih jezika.[12]'
SENTENCE_SIN = 'ශ්‍රී ලංකාවේ ප්‍රධාන ජාතිය වන සිංහල ජනයාගේ මව් බස සිංහල වෙයි.'
SENTENCE_SLK = 'Slovenčina patrí do skupiny západoslovanských jazykov (spolu s češtinou, poľštinou, hornou a dolnou lužickou srbčinou a kašubčinou).'
SENTENCE_SLV = TEXT_SLV[0]
SENTENCE_SOM = 'Af-Soomaali waa luqad Afro-Aasiyatik ah oo ay leedahay laanta Kushiitik .'
SENTENCE_SOT = 'Lebitso la "Sesotho" le bolela meetlo ea batho ba buang puo e bitsoang Sesotho.'
SENTENCE_DSB = 'Dolnoserbšćina, dolnoserbska rěc (nimski Niedersorbisch abo teke Wendisch, pólski język dolnołużycki, česki dolnolužická srbština) jo jadna z dweju rěcowu Serbow, kotaraž se wužywa w Dolnej Łužycy, w pódpołdnjowej Bramborskej, na pódzajtšu Nimskej.'
SENTENCE_HSB = 'Hornjoserbšćina je zapadosłowjanska rěč, kotraž so w Hornjej Łužicy wokoło městow Budyšin, Kamjenc a Wojerecy rěči.'
SENTENCE_SPA = TEXT_SPA[0]
SENTENCE_SWA = 'Kiswahili ni lugha ya Kibantu yenye misamiati mingi ya Kiarabu (35%[1]), lakini sasa ya Kiingereza pia (10%), inayozungumzwa katika eneo kubwa la Afrika ya Mashariki.'
SENTENCE_SWE = TEXT_SWE[0]
SENTENCE_TGL = 'Ang wikang Tagalog[1] (Baybayin: ᜏᜒᜃᜆᜄᜎᜓ), o ang Tagalog, ay isa sa mga pinakaginagamit na wika ng Pilipinas.'
SENTENCE_TGK = 'Забони тоҷикӣ — забоне, ки дар Эрон: форсӣ, ва дар Афғонистон дарӣ номида мешавад, забони давлатии кишварҳои Тоҷикистон, Эрон ва Афғонистон мебошад.'
SENTENCE_TAM = 'தமிழ் (Tamil language) தமிழர்களினதும் தமிழ் பேசும் பலரின் தாய்மொழி ஆகும்.'
SENTENCE_TAT = 'Татар теле — татарларның милли теле, Татарстанның дәүләт теле, таралышы буенча Россиядә икенче тел.'
SENTENCE_TEL = 'తెలుగు అనేది ద్రావిడ భాషల కుటుంబానికి చెందిన భాష.'
SENTENCE_TDT = "Tetun (iha portugés: tétum; iha inglés: Tetum) ne'e lian nasionál no ko-ofisiál Timór Lorosa'e nian."
SENTENCE_THA = TEXT_THA[0]
SENTENCE_BOD = TEXT_BOD[0]
SENTENCE_TIR = 'ትግርኛ ኣብ ኤርትራን ኣብ ሰሜናዊ ኢትዮጵያን ኣብ ክልል ትግራይ ዝዝረብ ሴማዊ ቋንቋ እዩ።'
SENTENCE_TSN = 'Setswana ke teme e e buiwang mo mafatsheng a Aforika Borwa, Botswana, Namibia le Zimbabwe.'
SENTENCE_TUR = TEXT_TUR[0]
SENTENCE_UKR = TEXT_UKR[0]
SENTENCE_URD = 'اُردُو یا لشکری زبان[8] برصغیر کی معیاری زبانوں میں سے ایک ہے۔'
SENTENCE_VIE = TEXT_VIE[0]
SENTENCE_CYM = "Aelod o'r gangen Frythonaidd o'r ieithoedd Celtaidd a siaredir yn frodorol yng Nghymru, gan Gymry a phobl eraill ar wasgar yn Lloegr, a chan gymuned fechan yn Y Wladfa, yr Ariannin[7] yw'r Gymraeg (hefyd Cymraeg heb y fannod)."
SENTENCE_YOR = 'Èdè Yorùbá Ni èdè tí ó ṣàkójọ pọ̀ gbogbo kú oótu o-ò-jíire bí, níapá ìwọ̀ Oòrùn ilẹ̀ Nàìjíríà, tí a bá wo èdè Yorùbá, àwọn onímọ̀ pín èdè náà sábẹ́ ẹ̀yà Kwa nínú ẹbí èdè Niger-Congo.'
SENTENCE_ZUL = 'Zulu /ˈzuːluː/, noma isiZulu wulimi lwabantu base Ningizimu neAfrika abayingxenye yamaNguni.'
SENTENCE_OTHER = SENTENCE_ENG_US
