# ----------------------------------------------------------------------
# GitHub: Issue template - Bug reports
# Copyright (C) 2018-2025  Ye Lei (叶磊)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# ----------------------------------------------------------------------

name: Bug Report
description: File a bug report.
title: "[Bug] "

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    attributes:
      label: Current behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        1. With this config...
        1. Run '...'
        1. See error...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Relevant error messages
      description: Please copy and paste any relevant error messages. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Wordless version
      description: What version of Wordless are you using?
      options:
        - 3.6.0
        - 3.5.0
        - 3.4.0
        - 3.3.0
        - 3.2.0
        - 3.1.0
        - 3.0.0
        - 2.3.0
        - 2.2.0
        - 2.1.0
        - 2.0.0
        - 1.5.0
        - 1.4.0
        - 1.3.0
        - 1.2.0
        - 1.1.0
        - 1.0.0
        - Development
        - Other
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Operating system
      description: What operating system(s) do you use?
      multiple: true
      options:
        - Windows
        - macOS (Apple Silicon-based)
        - macOS (Intel-based)
        - Ubuntu
        - Debian
        - Arch Linux
        - Other
    validations:
      required: true

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true

  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/BLKSerene/Wordless/blob/main/CODE_OF_CONDUCT.md). 
      options:
        - label: I agree to follow this Wordless's Code of Conduct
          required: true
