#
# Wordless: Tagsets - spaCy Norwegian Bokmål Tagset
#
# Copyright (C) 2018-2020  Ye Lei (叶磊)
#
# This source file is licensed under GNU GPLv3.
# For details, see: https://github.com/BLKSerene/Wordless/blob/master/LICENSE.txt
#
# All other rights reserved.
#

#
# spaCy Norwegian Bokmål Tagset: https://github.com/explosion/spaCy/tree/master/spacy/lang/nb/tag_map.py
#
# Universal POS Tags: http://universaldependencies.org/u/pos/all.html
#

mappings = [
    ['ADJ__Case=Gen|Definite=Def|Degree=Pos|Number=Sing', 'ADJ', '', ''],
    ['ADJ__Case=Gen|Definite=Def|Number=Sing', 'ADJ', '', ''],
    ['ADJ__Case=Gen|Definite=Ind|Degree=Pos|Gender=Neut|Number=Sing', 'ADJ', '', ''],
    ['ADJ__Case=Gen|Definite=Ind|Degree=Pos|Number=Sing', 'ADJ', '', ''],
    ['ADJ__Case=Gen|Degree=Cmp', 'ADJ', '', ''],
    ['ADJ__Case=Gen|Degree=Pos|Number=Plur', 'ADJ', '', ''],
    ['ADJ__Definite=Def|Degree=Pos|Gender=Masc|Number=Sing', 'ADJ', '', ''],
    ['ADJ__Definite=Def|Degree=Pos|Number=Sing', 'ADJ', '', ''],
    ['ADJ__Definite=Def|Degree=Sup', 'ADJ', '', ''],
    ['ADJ__Definite=Def|Number=Sing', 'ADJ', '', ''],
    ['ADJ__Definite=Ind|Degree=Pos', 'ADJ', '', ''],
    ['ADJ__Definite=Ind|Degree=Pos|Gender=Masc|Number=Sing', 'ADJ', '', ''],
    ['ADJ__Definite=Ind|Degree=Pos|Gender=Neut|Number=Sing', 'ADJ', '', ''],
    ['ADJ__Definite=Ind|Degree=Pos|Number=Sing', 'ADJ', '', ''],
    ['ADJ__Definite=Ind|Degree=Sup', 'ADJ', '', ''],
    ['ADJ__Definite=Ind|Gender=Masc|Number=Sing', 'ADJ', '', ''],
    ['ADJ__Definite=Ind|Gender=Neut|Number=Sing', 'ADJ', '', ''],
    ['ADJ__Definite=Ind|Number=Sing', 'ADJ', '', ''],
    ['ADJ__Degree=Cmp', 'ADJ', '', ''],
    ['ADJ__Degree=Pos', 'ADJ', '', ''],
    ['ADJ__Degree=Pos|Number=Plur', 'ADJ', '', ''],
    ['ADJ__Degree=Sup', 'ADJ', '', ''],
    ['ADJ__Number=Plur', 'ADJ', '', ''],
    ['ADJ__Number=Plur|VerbForm=Part', 'ADJ', '', ''],
    ['ADJ__Number=Sing', 'ADJ', '', ''],
    ['ADJ___', 'ADJ', '', ''],

    ['ADP___', 'ADP', '', ''],

    ['ADV___', 'ADV', '', ''],
    ['ADV__Gender=Masc', 'ADV', '', ''],

    ['AUX__Mood=Imp|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Ind|Tense=Past|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Ind|Tense=Pres|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Ind|Tense=Pres|VerbForm=Fin|Voice=Pass', 'AUX', '', ''],
    ['AUX__VerbForm=Inf', 'AUX', '', ''],
    ['AUX__VerbForm=Inf|Voice=Pass', 'AUX', '', ''],
    ['AUX__VerbForm=Part', 'AUX', '', ''],

    ['CONJ___', 'CONJ', '', ''],
    ['SCONJ___', 'SCONJ', '', ''],

    ['DET__Case=Gen|Definite=Ind|Gender=Masc|Number=Sing|PronType=Dem', 'DET', '', ''],
    ['DET__Case=Gen|Gender=Fem|Number=Sing|PronType=Dem', 'DET', '', ''],
    ['DET__Case=Gen|Gender=Masc|Number=Sing', 'DET', '', ''],
    ['DET__Case=Gen|Gender=Masc|Number=Sing|PronType=Dem', 'DET', '', ''],
    ['DET__Case=Gen|Gender=Neut|Number=Sing|PronType=Dem', 'DET', '', ''],
    ['DET__Case=Gen|Number=Plur', 'DET', '', ''],
    ['DET__Case=Gen|Number=Plur|PronType=Dem', 'DET', '', ''],
    ['DET__Definite=Def', 'DET', '', ''],
    ['DET__Definite=Def|Number=Sing|PronType=Dem', 'DET', '', ''],
    ['DET__Definite=Def|PronType=Dem', 'DET', '', ''],
    ['DET__Definite=Ind|Gender=Fem|Number=Sing', 'DET', '', ''],
    ['DET__Definite=Ind|Gender=Fem|Number=Sing|PronType=Dem', 'DET', '', ''],
    ['DET__Definite=Ind|Gender=Masc|Number=Sing', 'DET', '', ''],
    ['DET__Definite=Ind|Gender=Masc|Number=Sing|PronType=Dem', 'DET', '', ''],
    ['DET__Definite=Ind|Gender=Neut|Number=Sing', 'DET', '', ''],
    ['DET__Definite=Ind|Gender=Neut|Number=Sing|PronType=Dem', 'DET', '', ''],
    ['DET__Degree=Pos|Number=Plur', 'DET', '', ''],
    ['DET__Gender=Fem|Number=Sing', 'DET', '', ''],
    ['DET__Gender=Fem|Number=Sing|Poss=Yes', 'DET', '', ''],
    ['DET__Gender=Fem|Number=Sing|PronType=Dem', 'DET', '', ''],
    ['DET__Gender=Fem|Number=Sing|PronType=Int', 'DET', '', ''],
    ['DET__Gender=Masc|Number=Sing', 'DET', '', ''],
    ['DET__Gender=Masc|Number=Sing|Poss=Yes', 'DET', '', ''],
    ['DET__Gender=Masc|Number=Sing|PronType=Dem', 'DET', '', ''],
    ['DET__Gender=Masc|Number=Sing|PronType=Int', 'DET', '', ''],
    ['DET__Gender=Neut|Number=Sing', 'DET', '', ''],
    ['DET__Gender=Neut|Number=Sing|Poss=Yes', 'DET', '', ''],
    ['DET__Gender=Neut|Number=Sing|PronType=Dem', 'DET', '', ''],
    ['DET__Gender=Neut|Number=Sing|PronType=Int', 'DET', '', ''],
    ['DET__Number=Plur', 'DET', '', ''],
    ['DET__Number=Plur|Poss=Yes', 'DET', '', ''],
    ['DET__Number=Plur|Poss=Yes|PronType=Rcp', 'DET', '', ''],
    ['DET__Number=Plur|PronType=Dem', 'DET', '', ''],
    ['DET__Number=Plur|PronType=Int', 'DET', '', ''],
    ['DET___', 'DET', '', ''],

    ['INTJ___', 'INTJ', '', ''],

    ['NOUN__Case=Gen', 'NOUN', '', ''],
    ['NOUN__Case=Gen|Definite=Def|Gender=Fem|Number=Plur', 'NOUN', '', ''],
    ['NOUN__Case=Gen|Definite=Def|Gender=Fem|Number=Sing', 'NOUN', '', ''],
    ['NOUN__Case=Gen|Definite=Def|Gender=Masc|Number=Plur', 'NOUN', '', ''],
    ['NOUN__Case=Gen|Definite=Def|Gender=Masc|Number=Sing', 'NOUN', '', ''],
    ['NOUN__Case=Gen|Definite=Def|Gender=Neut|Number=Plur', 'NOUN', '', ''],
    ['NOUN__Case=Gen|Definite=Def|Gender=Neut|Number=Sing', 'NOUN', '', ''],
    ['NOUN__Case=Gen|Definite=Ind|Gender=Fem|Number=Plur', 'NOUN', '', ''],
    ['NOUN__Case=Gen|Definite=Ind|Gender=Fem|Number=Sing', 'NOUN', '', ''],
    ['NOUN__Case=Gen|Definite=Ind|Gender=Masc|Number=Plur', 'NOUN', '', ''],
    ['NOUN__Case=Gen|Definite=Ind|Gender=Masc|Number=Sing', 'NOUN', '', ''],
    ['NOUN__Case=Gen|Definite=Ind|Gender=Neut|Number=Plur', 'NOUN', '', ''],
    ['NOUN__Case=Gen|Definite=Ind|Gender=Neut|Number=Sing', 'NOUN', '', ''],
    ['NOUN__Case=Gen|Gender=Fem', 'NOUN', '', ''],
    ['NOUN__Definite=Def,Ind|Gender=Masc|Number=Plur,Sing', 'NOUN', '', ''],
    ['NOUN__Definite=Def,Ind|Gender=Masc|Number=Sing', 'NOUN', '', ''],
    ['NOUN__Definite=Def,Ind|Gender=Neut|Number=Plur,Sing', 'NOUN', '', ''],
    ['NOUN__Definite=Def|Gender=Fem|Number=Plur', 'NOUN', '', ''],
    ['NOUN__Definite=Def|Gender=Fem|Number=Sing', 'NOUN', '', ''],
    ['NOUN__Definite=Def|Gender=Masc|Number=Plur', 'NOUN', '', ''],
    ['NOUN__Definite=Def|Gender=Masc|Number=Sing', 'NOUN', '', ''],
    ['NOUN__Definite=Def|Gender=Neut|Number=Plur', 'NOUN', '', ''],
    ['NOUN__Definite=Def|Gender=Neut|Number=Sing', 'NOUN', '', ''],
    ['NOUN__Definite=Def|Number=Plur', 'NOUN', '', ''],
    ['NOUN__Definite=Ind|Gender=Fem|Number=Plur', 'NOUN', '', ''],
    ['NOUN__Definite=Ind|Gender=Fem|Number=Sing', 'NOUN', '', ''],
    ['NOUN__Definite=Ind|Gender=Masc', 'NOUN', '', ''],
    ['NOUN__Definite=Ind|Gender=Masc|Number=Plur', 'NOUN', '', ''],
    ['NOUN__Definite=Ind|Gender=Masc|Number=Sing', 'NOUN', '', ''],
    ['NOUN__Definite=Ind|Gender=Neut|Number=Plur', 'NOUN', '', ''],
    ['NOUN__Definite=Ind|Gender=Neut|Number=Sing', 'NOUN', '', ''],
    ['NOUN__Definite=Ind|Number=Plur', 'NOUN', '', ''],
    ['NOUN__Definite=Ind|Number=Sing', 'NOUN', '', ''],
    ['NOUN__Gender=Fem', 'NOUN', '', ''],
    ['NOUN__Gender=Masc', 'NOUN', '', ''],
    ['NOUN__Gender=Masc|Number=Sing', 'NOUN', '', ''],
    ['NOUN__Gender=Neut', 'NOUN', '', ''],
    ['NOUN__Number=Plur', 'NOUN', '', ''],
    ['NOUN___', 'NOUN', '', ''],

    ['PROPN__Case=Gen', 'PROPN', '', ''],
    ['PROPN__Case=Gen|Gender=Fem', 'PROPN', '', ''],
    ['PROPN__Case=Gen|Gender=Masc', 'PROPN', '', ''],
    ['PROPN__Case=Gen|Gender=Neut', 'PROPN', '', ''],
    ['PROPN__Gender=Fem', 'PROPN', '', ''],
    ['PROPN__Gender=Masc', 'PROPN', '', ''],
    ['PROPN__Gender=Neut', 'PROPN', '', ''],
    ['PROPN___', 'PROPN', '', ''],

    ['NUM__Case=Gen|Number=Plur', 'NUM', '', ''],
    ['NUM__Definite=Def', 'NUM', '', ''],
    ['NUM__Definite=Def|Number=Sing', 'NUM', '', ''],
    ['NUM__Gender=Fem|Number=Sing', 'NUM', '', ''],
    ['NUM__Gender=Masc|Number=Sing', 'NUM', '', ''],
    ['NUM__Gender=Neut|Number=Sing', 'NUM', '', ''],
    ['NUM__Number=Plur', 'NUM', '', ''],
    ['NUM__Number=Sing', 'NUM', '', ''],
    ['NUM___', 'NUM', '', ''],

    ['PART___', 'PART', '', ''],

    ['PRON__Animacy=Anim|Case=Acc|Gender=Fem|Number=Sing|Person=3|PronType=Prs', 'PRON', '', ''],
    ['PRON__Animacy=Anim|Case=Acc|Gender=Masc|Number=Sing|Person=3|PronType=Prs', 'PRON', '', ''],
    ['PRON__Animacy=Anim|Case=Acc|Number=Plur|Person=1|PronType=Prs', 'PRON', '', ''],
    ['PRON__Animacy=Anim|Case=Acc|Number=Plur|Person=2|PronType=Prs', 'PRON', '', ''],
    ['PRON__Animacy=Anim|Case=Acc|Number=Sing|Person=1|PronType=Prs', 'PRON', '', ''],
    ['PRON__Animacy=Anim|Case=Acc|Number=Sing|Person=2|PronType=Prs', 'PRON', '', ''],
    ['PRON__Animacy=Anim|Case=Gen,Nom|Number=Sing|PronType=Prs', 'PRON', '', ''],
    ['PRON__Animacy=Anim|Case=Gen|Number=Sing|PronType=Prs', 'PRON', '', ''],
    ['PRON__Animacy=Anim|Case=Nom|Gender=Fem|Number=Sing|Person=3|PronType=Prs', 'PRON', '', ''],
    ['PRON__Animacy=Anim|Case=Nom|Gender=Masc|Number=Sing|Person=3|PronType=Prs', 'PRON', '', ''],
    ['PRON__Animacy=Anim|Case=Nom|Number=Plur|Person=1|PronType=Prs', 'PRON', '', ''],
    ['PRON__Animacy=Anim|Case=Nom|Number=Plur|Person=2|PronType=Prs', 'PRON', '', ''],
    ['PRON__Animacy=Anim|Case=Nom|Number=Sing|Person=1|PronType=Prs', 'PRON', '', ''],
    ['PRON__Animacy=Anim|Case=Nom|Number=Sing|Person=2|PronType=Prs', 'PRON', '', ''],
    ['PRON__Animacy=Anim|Case=Nom|Number=Sing|PronType=Prs', 'PRON', '', ''],
    ['PRON__Animacy=Anim|Number=Plur|PronType=Rcp', 'PRON', '', ''],
    ['PRON__Animacy=Anim|Number=Sing|PronType=Prs', 'PRON', '', ''],
    ['PRON__Animacy=Anim|Poss=Yes|PronType=Int', 'PRON', '', ''],
    ['PRON__Animacy=Anim|PronType=Int', 'PRON', '', ''],
    ['PRON__Case=Acc|Number=Plur|Person=3|PronType=Prs', 'PRON', '', ''],
    ['PRON__Case=Acc|Reflex=Yes', 'PRON', '', ''],
    ['PRON__Case=Nom|Number=Plur|Person=3|PronType=Prs', 'PRON', '', ''],
    ['PRON__Case=Gen|Number=Plur|Person=3|PronType=Prs', 'PRON', '', ''],
    ['PRON__Gender=Fem,Masc|Number=Sing|Person=3|PronType=Prs', 'PRON', '', ''],
    ['PRON__Gender=Neut|Number=Sing|Person=3|PronType=Prs', 'PRON', '', ''],
    ['PRON__Number=Plur|Person=3|PronType=Prs', 'PRON', '', ''],
    ['PRON__Number=Sing', 'PRON', '', ''],
    ['PRON__PronType=Int', 'PRON', '', ''],
    ['PRON___', 'PRON', '', ''],

    ['VERB__Definite=Ind|Number=Sing', 'VERB', '', ''],
    ['VERB__Mood=Imp|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Ind|Tense=Past|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Ind|Tense=Past|VerbForm=Fin|Voice=Pass', 'VERB', '', ''],
    ['VERB__Mood=Ind|Tense=Pres|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Ind|Tense=Pres|VerbForm=Fin|Voice=Pass', 'VERB', '', ''],
    ['VERB__VerbForm=Inf', 'VERB', '', ''],
    ['VERB__VerbForm=Inf|Voice=Pass', 'VERB', '', ''],
    ['VERB__VerbForm=Part', 'VERB', '', ''],
    ['VERB___', 'VERB', '', ''],

    ['PUNCT___', 'PUNCT', '', ''],
    ['SYM___', 'SYM', '', ''],

    ['X___', 'X', '', '']
]
