#
# Wordless: Tagsets - spaCy French Tagset
#
# Copyright (C) 2018-2020  Ye Lei (叶磊)
#
# This source file is licensed under GNU GPLv3.
# For details, see: https://github.com/BLKSerene/Wordless/blob/master/LICENSE.txt
#
# All other rights reserved.
#

#
# spaCy French Tagset: https://github.com/explosion/spaCy/blob/master/spacy/lang/fr/tag_map.py
#
# Universal POS Tags: http://universaldependencies.org/u/pos/all.html
#

mappings = [
    ['ADJ__Gender=Fem|Number=Plur', 'ADJ', '', ''],
    ['ADJ__Gender=Fem|Number=Plur|NumType=Ord', 'ADJ', '', ''],
    ['ADJ__Gender=Fem|Number=Sing', 'ADJ', '', ''],
    ['ADJ__Gender=Fem|Number=Sing|NumType=Ord', 'ADJ', '', ''],
    ['ADJ__Gender=Masc', 'ADJ', '', ''],
    ['ADJ__Gender=Masc|Number=Plur', 'ADJ', '', ''],
    ['ADJ__Gender=Masc|Number=Plur|NumType=Ord', 'ADJ', '', ''],
    ['ADJ__Gender=Masc|Number=Sing', 'ADJ', '', ''],
    ['ADJ__Gender=Masc|Number=Sing|NumType=Card', 'ADJ', '', ''],
    ['ADJ__Gender=Masc|Number=Sing|NumType=Ord', 'ADJ', '', ''],
    ['ADJ__NumType=Card', 'ADJ', '', ''],
    ['ADJ__NumType=Ord', 'ADJ', '', ''],
    ['ADJ__Number=Plur', 'ADJ', '', ''],
    ['ADJ__Number=Sing', 'ADJ', '', ''],
    ['ADJ__Number=Sing|NumType=Ord', 'ADJ', '', ''],
    ['ADJ___', 'ADJ', '', ''],

    ['ADP__Gender=Fem|Number=Plur|Person=3', 'ADP', '', ''],
    ['ADP__Gender=Masc|Number=Plur|Person=3', 'ADP', '', ''],
    ['ADP__Gender=Masc|Number=Sing|Person=3', 'ADP', '', ''],
    ['ADP___', 'ADP', '', ''],

    ['ADV__Polarity=Neg', 'ADV', '', ''],
    ['ADV__PronType=Int', 'ADV', '', ''],
    ['ADV___', 'ADV', '', ''],

    ['AUX__Gender=Fem|Number=Plur|Tense=Past|VerbForm=Part', 'AUX', '', ''],
    ['AUX__Gender=Fem|Number=Plur|Tense=Past|VerbForm=Part|Voice=Pass', 'AUX', '', ''],
    ['AUX__Gender=Fem|Number=Sing|Tense=Past|VerbForm=Part', 'AUX', '', ''],
    ['AUX__Gender=Fem|Number=Sing|Tense=Past|VerbForm=Part|Voice=Pass', 'AUX', '', ''],
    ['AUX__Gender=Masc|Number=Plur|Tense=Past|VerbForm=Part', 'AUX', '', ''],
    ['AUX__Gender=Masc|Number=Plur|Tense=Past|VerbForm=Part|Voice=Pass', 'AUX', '', ''],
    ['AUX__Gender=Masc|Number=Sing|Tense=Past|VerbForm=Part', 'AUX', '', ''],
    ['AUX__Gender=Masc|Number=Sing|Tense=Past|VerbForm=Part|Voice=Pass', 'AUX', '', ''],
    ['AUX__Mood=Cnd|Number=Plur|Person=1|Tense=Pres|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Cnd|Number=Plur|Person=2|Tense=Pres|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Cnd|Number=Plur|Person=3|Tense=Pres|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Cnd|Number=Sing|Person=1|Tense=Pres|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Cnd|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Imp|Number=Plur|Person=2|Tense=Pres|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Ind|Number=Plur|Person=1|Tense=Fut|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Ind|Number=Plur|Person=1|Tense=Imp|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Ind|Number=Plur|Person=1|Tense=Pres|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Ind|Number=Plur|Person=2|Tense=Pres|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Ind|Number=Plur|Person=3|Tense=Fut|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Ind|Number=Plur|Person=3|Tense=Imp|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Ind|Number=Plur|Person=3|Tense=Past|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Ind|Number=Plur|Person=3|Tense=Pres|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Ind|Number=Sing|Person=1|Tense=Imp|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Ind|Number=Sing|Person=1|Tense=Pres|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Ind|Number=Sing|Person=2|Tense=Imp|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Ind|Number=Sing|Person=3|Tense=Fut|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Ind|Number=Sing|Person=3|Tense=Imp|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Ind|Number=Sing|Person=3|Tense=Past|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Sub|Number=Plur|Person=1|Tense=Pres|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Sub|Number=Plur|Person=2|Tense=Pres|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Sub|Number=Plur|Person=3|Tense=Pres|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Sub|Number=Sing|Person=1|Tense=Pres|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Mood=Sub|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin', 'AUX', '', ''],
    ['AUX__Number=Sing|Tense=Past|VerbForm=Part|Voice=Pass', 'AUX', '', ''],
    ['AUX__Tense=Past|VerbForm=Part', 'AUX', '', ''],
    ['AUX__Tense=Pres|VerbForm=Part', 'AUX', '', ''],
    ['AUX__VerbForm=Inf', 'AUX', '', ''],

    ['CCONJ___', 'CCONJ', '', ''],
    ['SCONJ___', 'SCONJ', '', ''],

    ['DET__Definite=Def|Gender=Fem|Number=Sing|PronType=Art', 'DET', '', ''],
    ['DET__Definite=Def|Gender=Masc|Number=Sing|PronType=Art', 'DET', '', ''],
    ['DET__Definite=Def|Number=Plur|PronType=Art', 'DET', '', ''],
    ['DET__Definite=Def|Number=Sing|PronType=Art', 'DET', '', ''],
    ['DET__Definite=Ind|Gender=Fem|Number=Plur|PronType=Art', 'DET', '', ''],
    ['DET__Definite=Ind|Gender=Fem|Number=Sing|PronType=Art', 'DET', '', ''],
    ['DET__Definite=Ind|Gender=Masc|Number=Plur|PronType=Art', 'DET', '', ''],
    ['DET__Definite=Ind|Gender=Masc|Number=Sing|PronType=Art', 'DET', '', ''],
    ['DET__Definite=Ind|Number=Plur|PronType=Art', 'DET', '', ''],
    ['DET__Definite=Ind|Number=Sing|PronType=Art', 'DET', '', ''],
    ['DET__Gender=Fem|Number=Plur', 'DET', '', ''],
    ['DET__Gender=Fem|Number=Plur|PronType=Int', 'DET', '', ''],
    ['DET__Gender=Fem|Number=Sing', 'DET', '', ''],
    ['DET__Gender=Fem|Number=Sing|Poss=Yes', 'DET', '', ''],
    ['DET__Gender=Fem|Number=Sing|PronType=Dem', 'DET', '', ''],
    ['DET__Gender=Fem|Number=Sing|PronType=Int', 'DET', '', ''],
    ['DET__Gender=Masc|Number=Plur', 'DET', '', ''],
    ['DET__Gender=Masc|Number=Sing', 'DET', '', ''],
    ['DET__Gender=Masc|Number=Sing|PronType=Dem', 'DET', '', ''],
    ['DET__Gender=Masc|Number=Sing|PronType=Int', 'DET', '', ''],
    ['DET__Number=Plur', 'DET', '', ''],
    ['DET__Number=Plur|Poss=Yes', 'DET', '', ''],
    ['DET__Number=Plur|PronType=Dem', 'DET', '', ''],
    ['DET__Number=Sing', 'DET', '', ''],
    ['DET__Number=Sing|Poss=Yes', 'DET', '', ''],
    ['DET___', 'DET', '', ''],

    ['INTJ___', 'INTJ', '', ''],

    ['NOUN__Gender=Fem', 'NOUN', '', ''],
    ['NOUN__Gender=Fem|Number=Plur', 'NOUN', '', ''],
    ['NOUN__Gender=Fem|Number=Sing', 'NOUN', '', ''],
    ['NOUN__Gender=Masc', 'NOUN', '', ''],
    ['NOUN__Gender=Masc|Number=Plur', 'NOUN', '', ''],
    ['NOUN__Gender=Masc|Number=Plur|NumType=Card', 'NOUN', '', ''],
    ['NOUN__Gender=Masc|Number=Sing', 'NOUN', '', ''],
    ['NOUN__Gender=Masc|Number=Sing|NumType=Card', 'NOUN', '', ''],
    ['NOUN__NumType=Card', 'NOUN', '', ''],
    ['NOUN__Number=Plur', 'NOUN', '', ''],
    ['NOUN__Number=Sing', 'NOUN', '', ''],
    ['NOUN___', 'NOUN', '', ''],

    ['PROPN__Gender=Fem|Number=Plur', 'PROPN', '', ''],
    ['PROPN__Gender=Fem|Number=Sing', 'PROPN', '', ''],
    ['PROPN__Gender=Masc', 'PROPN', '', ''],
    ['PROPN__Gender=Masc|Number=Plur', 'PROPN', '', ''],
    ['PROPN__Gender=Masc|Number=Sing', 'PROPN', '', ''],
    ['PROPN__Number=Plur', 'PROPN', '', ''],
    ['PROPN__Number=Sing', 'PROPN', '', ''],
    ['PROPN___', 'PROPN', '', ''],

    ['NUM__Gender=Masc|Number=Plur|NumType=Card', 'NUM', '', ''],
    ['NUM__NumType=Card', 'NUM', '', ''],

    ['PART___', 'PART', '', ''],

    ['PRON__Gender=Fem|Number=Plur', 'PRON', '', ''],
    ['PRON__Gender=Fem|Number=Plur|Person=3', 'PRON', '', ''],
    ['PRON__Gender=Fem|Number=Plur|Person=3|PronType=Prs', 'PRON', '', ''],
    ['PRON__Gender=Fem|Number=Plur|Person=3|PronType=Rel', 'PRON', '', ''],
    ['PRON__Gender=Fem|Number=Plur|PronType=Dem', 'PRON', '', ''],
    ['PRON__Gender=Fem|Number=Plur|PronType=Rel', 'PRON', '', ''],
    ['PRON__Gender=Fem|Number=Sing|Person=3', 'PRON', '', ''],
    ['PRON__Gender=Fem|Number=Sing|Person=3|PronType=Prs', 'PRON', '', ''],
    ['PRON__Gender=Fem|Number=Sing|PronType=Dem', 'PRON', '', ''],
    ['PRON__Gender=Fem|Number=Sing|PronType=Rel', 'PRON', '', ''],
    ['PRON__Gender=Fem|PronType=Rel', 'PRON', '', ''],
    ['PRON__Gender=Masc|Number=Plur', 'PRON', '', ''],
    ['PRON__Gender=Masc|Number=Plur|Person=3', 'PRON', '', ''],
    ['PRON__Gender=Masc|Number=Plur|Person=3|PronType=Prs', 'PRON', '', ''],
    ['PRON__Gender=Masc|Number=Plur|Person=3|PronType=Rel', 'PRON', '', ''],
    ['PRON__Gender=Masc|Number=Plur|PronType=Dem', 'PRON', '', ''],
    ['PRON__Gender=Masc|Number=Plur|PronType=Rel', 'PRON', '', ''],
    ['PRON__Gender=Masc|Number=Sing', 'PRON', '', ''],
    ['PRON__Gender=Masc|Number=Sing|Person=3', 'PRON', '', ''],
    ['PRON__Gender=Masc|Number=Sing|Person=3|PronType=Dem', 'PRON', '', ''],
    ['PRON__Gender=Masc|Number=Sing|Person=3|PronType=Prs', 'PRON', '', ''],
    ['PRON__Gender=Masc|Number=Sing|PronType=Dem', 'PRON', '', ''],
    ['PRON__Gender=Masc|Number=Sing|PronType=Rel', 'PRON', '', ''],
    ['PRON__Gender=Masc|PronType=Rel', 'PRON', '', ''],
    ['PRON__NumType=Card|PronType=Rel', 'PRON', '', ''],
    ['PRON__Number=Plur|Person=1', 'PRON', '', ''],
    ['PRON__Number=Plur|Person=1|PronType=Prs', 'PRON', '', ''],
    ['PRON__Number=Plur|Person=1|Reflex=Yes', 'PRON', '', ''],
    ['PRON__Number=Plur|Person=2', 'PRON', '', ''],
    ['PRON__Number=Plur|Person=2|PronType=Prs', 'PRON', '', ''],
    ['PRON__Number=Plur|Person=2|Reflex=Yes', 'PRON', '', ''],
    ['PRON__Number=Plur|Person=3', 'PRON', '', ''],
    ['PRON__Number=Plur|PronType=Rel', 'PRON', '', ''],
    ['PRON__Number=Sing|Person=1', 'PRON', '', ''],
    ['PRON__Number=Sing|Person=1|PronType=Prs', 'PRON', '', ''],
    ['PRON__Number=Sing|Person=1|Reflex=Yes', 'PRON', '', ''],
    ['PRON__Number=Sing|Person=2|PronType=Prs', 'PRON', '', ''],
    ['PRON__Number=Sing|Person=3', 'PRON', '', ''],
    ['PRON__Number=Sing|PronType=Dem', 'PRON', '', ''],
    ['PRON__Number=Sing|PronType=Rel', 'PRON', '', ''],
    ['PRON__Person=3', 'PRON', '', ''],
    ['PRON__Person=3|Reflex=Yes', 'PRON', '', ''],
    ['PRON__PronType=Int', 'PRON', '', ''],
    ['PRON__PronType=Rel', 'PRON', '', ''],
    ['PRON___', 'PRON', '', ''],

    ['VERB__Gender=Fem|Number=Plur|Tense=Past|VerbForm=Part', 'VERB', '', ''],
    ['VERB__Gender=Fem|Number=Plur|Tense=Past|VerbForm=Part|Voice=Pass', 'VERB', '', ''],
    ['VERB__Gender=Fem|Number=Sing|Tense=Past|VerbForm=Part', 'VERB', '', ''],
    ['VERB__Gender=Fem|Number=Sing|Tense=Past|VerbForm=Part|Voice=Pass', 'VERB', '', ''],
    ['VERB__Gender=Masc|Number=Plur|Tense=Past|VerbForm=Part', 'VERB', '', ''],
    ['VERB__Gender=Masc|Number=Plur|Tense=Past|VerbForm=Part|Voice=Pass', 'VERB', '', ''],
    ['VERB__Gender=Masc|Number=Sing|Tense=Past|VerbForm=Part', 'VERB', '', ''],
    ['VERB__Gender=Masc|Number=Sing|Tense=Past|VerbForm=Part|Voice=Pass', 'VERB', '', ''],
    ['VERB__Gender=Masc|Tense=Past|VerbForm=Part', 'VERB', '', ''],
    ['VERB__Gender=Masc|Tense=Past|VerbForm=Part|Voice=Pass', 'VERB', '', ''],
    ['VERB__Mood=Cnd|Number=Plur|Person=3|Tense=Pres|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Cnd|Number=Sing|Person=1|Tense=Pres|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Cnd|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Imp|Number=Plur|Person=1|Tense=Pres|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Imp|Number=Plur|Person=2|Tense=Pres|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Imp|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Ind|Number=Plur|Person=1|Tense=Fut|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Ind|Number=Plur|Person=1|Tense=Imp|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Ind|Number=Plur|Person=1|Tense=Pres|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Ind|Number=Plur|Person=2|Tense=Fut|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Ind|Number=Plur|Person=2|Tense=Imp|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Ind|Number=Plur|Person=2|Tense=Pres|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Ind|Number=Plur|Person=3|Tense=Fut|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Ind|Number=Plur|Person=3|Tense=Imp|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Ind|Number=Plur|Person=3|Tense=Past|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Ind|Number=Plur|Person=3|Tense=Pres|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Ind|Number=Sing|Person=1|Tense=Fut|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Ind|Number=Sing|Person=1|Tense=Imp|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Ind|Number=Sing|Person=1|Tense=Pres|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Ind|Number=Sing|Person=3|Tense=Fut|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Ind|Number=Sing|Person=3|Tense=Imp|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Ind|Number=Sing|Person=3|Tense=Past|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Ind|Person=3|Tense=Pres|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Ind|Person=3|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Ind|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Sub|Number=Plur|Person=3|Tense=Pres|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Sub|Number=Sing|Person=1|Tense=Pres|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Sub|Number=Sing|Person=3|Tense=Past|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Mood=Sub|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin', 'VERB', '', ''],
    ['VERB__Number=Plur|Tense=Past|VerbForm=Part', 'VERB', '', ''],
    ['VERB__Number=Plur|Tense=Past|VerbForm=Part|Voice=Pass', 'VERB', '', ''],
    ['VERB__Number=Sing|Tense=Past|VerbForm=Part', 'VERB', '', ''],
    ['VERB__Number=Sing|Tense=Past|VerbForm=Part|Voice=Pass', 'VERB', '', ''],
    ['VERB__Tense=Past|VerbForm=Part', 'VERB', '', ''],
    ['VERB__Tense=Past|VerbForm=Part|Voice=Pass', 'VERB', '', ''],
    ['VERB__Tense=Pres|VerbForm=Part', 'VERB', '', ''],
    ['VERB__VerbForm=Inf', 'VERB', '', ''],
    ['VERB__VerbForm=Part', 'VERB', '', ''],

    ['PUNCT___', 'PUNCT', '', ''],

    ['_SP', 'X', '', ''],
    ['X___', 'X', '', '']
]
